---
title: "07_clustering"
output: html_document
---

```{r}
for (pkg in c("tidyverse",  "data.table", "R.utils", "maditr", "stringr", "stringi", "dplyr", "ggplot2", "lubridate", "gt", "DataExplorer", "TraMineR", "TraMineRextras", "cluster")) {
  library(pkg, character.only = TRUE)
}
```


# Step 1. Formating sequence data
```{r}
bg_vet_job <- read.csv("data/04_bg_vet_job.csv")

bg_vet_job_seq <- bg_vet_job %>%
  select("id", "start_year", "end_year", "onet_job_zone")%>%
  group_by(id)%>%
  arrange(desc(onet_job_zone))%>%
  group_by(id)%>%
  distinct(id, start_year, end_year, .keep_all = TRUE)

# We need an auxillary table with the year of entering the job market to align the sequences
bg_vet_job_first <- bg_vet_job_seq %>% 
  select("id", "start_year") %>% group_by(id) %>% transmute(enter = min(start_year)) %>% distinct() %>% ungroup()

# The seqformat() function does not like any data that has been previously grouped. Here we are "resetting" the data so that it will pass through the function.
bg_vet_job_seq <- as.matrix(bg_vet_job_seq)
bg_vet_job_seq <- as.data.frame(bg_vet_job_seq)
bg_vet_job_first <- as.matrix(bg_vet_job_first)
bg_vet_job_first <- as.data.frame(bg_vet_job_first)


# The input for the function is the prepared sequence table. The data is in format SPELL and we are transforming to format STS. By setting process = TRUE we can align the sequences using the prepared auxillary table.
sts_vet <- seqformat(bg_vet_job_seq, from = "SPELL", to = "STS",
                     id = "id",  begin = "start_year", end = "end_year", 
                     status = "onet_job_zone", process = TRUE,
                     pdata = bg_vet_job_first, pvar = c("id", "enter"))
# Here we are renaming columns to be in format "yn" (year in the job market)
names(sts_vet) <- paste0("y", 1:100)

```

# Step 1. (alt)
## read in sequence data
```{r}
sts_vet <- read_csv("~/git/dspg20career/data/sts_vet.csv")%>%
  column_to_rownames("X1")
nrow(sts_vet) #number of veterans
```

# Step 2. Create sequence object
```{r}
#delete missing values at front and end
vet.seq <- seqdef(sts_vet, left="DEL", gaps="NA", right="DEL")
class(vet.seq)

#an example of three sequences
vet.seq[1, ]
vet.seq[2, ]
vet.seq[3, ]

#number of matching positions between 2 sequences
seqmpos(vet.seq[1, ], vet.seq[2, ]) 
seqmpos(vet.seq[2, ], vet.seq[3, ])

#length of the longest common prefix (LLCP) between sequence 1 and 2
seqLLCP(vet.seq[1, ], vet.seq[2, ])
seqLLCP(vet.seq[2, ], vet.seq[3, ])
```

# Step 3. Cost Matrix
```{r}
#substitution-cost matrix
#method="CONSTANT"/"TRATE"
cost_matrix_trate <- seqsubm(vet.seq, method = "TRATE", with.missing = TRUE)
cost_matrix_trate <- round(cost_matrix_trate, 2)
cost_matrix_trate

cost_matrix_constant <- seqsubm(vet.seq, method = "CONSTANT", with.missing = TRUE)
cost_matrix_constant
#optimal matching distance
# vet.seq.OM <- seqdist(vet.seq, method = "OM", sm = cost_matrix_constant)
# vet.seq.OM[1,2]  #optimal distance between sequence 1 and 2 (addition, deletion)
```

# Step 4. Distance Matrix
```{r}
#1. LCP (longest common prefix) distance  (distance matrix)
# LCP_distance <- 1- seqdist(vet.seq, method = "LCP", norm = TRUE)

#2. LCS (longest common subsequence) distance (distance matrix)
#treat missing in middle of the sequence as one state
# vet.lcs <- seqdist(vet.seq, method = "LCS", with.missing = TRUE)
# vet.lcs[1:10, 1:10]

#3. OM
vet.seq.OM <- seqdist(vet.seq, method = "OM", indel = 3, sm = cost_matrix_trate, with.missing = TRUE)

#The necessary size to store the matrix is roughly 453.5 Mb
object.size(vet.seq.OM)/1024^2

#glimpse of the distance matrix
round(vet.seq.OM[1:10, 1:10], 1)
```

# Step 5. Clustering
```{r}
#clustering
# start_time <- Sys.time()
# clusterward <- agnes(vet.seq.OM, diss = TRUE, method = "ward")
# end_time <- Sys.time()
#saveRDS(clusterward, file = "data/clusterward.rds")
#message("run time: ", end_time - start_time)
```

# Step 5.(alt) 
## Read in distance
```{r}
clusterward <- readRDS(file = "git/dspg20career/data/clusterward.rds")  #set your own directory

# clusterward <- readRDS(file = "/sfs/qumulo/qhome/zz3hs/git/dspg20career/data/clusterward.rds")
```

# Step 6. Visualize Clustering
```{r}
#dendrogram 
plot(clusterward, which.plots =2)

cluster3 <- cutree(clusterward, k=3)
cluster3 <- factor(cluster3, labels = c("Type 1",  "Type 2", "Type 3"))
table(cluster3)

#longitudinal plot
seqfplot(vet.seq, group = cluster3, pbarw = T)

#another cluster plot
seqmtplot(vet.seq, group = cluster3)
```

