---
title: "Results Section One"
description: "Regression Model Correlates Of Eviction Rates"
tags: ["policy", "socio-demographic"]
weight: 1
draft: false
output: html_document
---

```{css, echo=FALSE}
/* this chunnk of code centers all of the headings */
h1, h2, h3 {
  text-align: center;
}
```

##Modeling Census Tract Level Evictions: Correlates Of Eviction Rates

The sociodemographic variables shown, including race and income, mirror the spatial relationships seen in eviction rates. In this section, we use a regression model to study whether and how eviction rates are affected by these variables. We find that the following variables are significantly associated with eviction rates.

Socio-demographic:
	
* Percentage of tract that is Black or African American (+), 
* Percentage of tract aged 16+ who are unemployed (+), 
* Census tract poverty rate (+), 
* Percentage of tract with a bachelor’s degree (-)

This suggests that African Americans are more likely to live in communities with high eviction rates. As also seen in previous work on evictions rates (Scanlon and Devine 2001; Pribesh and Downey 1999; Kull, Coley, and Lynch 2016; Ersing, Sutphen, and Loeffler 2009** ) poverty rates, and education are also positively associated. Unemployment deserves a special mention because it is positively associated and as the Covid-19 epidemic starts to spread across communities in Richmond, this positive association could suggest higher levels of eviction in Richmond in the absence of an eviction moratorium. 

One of the main contributions of our analysis is to control for state-level policy factors. And, indeed we find that they are significantly associated with eviction rates.

State policy factors:

* Number of exemptions to Fair Housing Laws (landlord-friendly) (+), 
* Number of exemptions landlords have from state landlord-tenant law (landlord-friendly) (+), 
* Number of legal remedies available to tenants (-), 
* Number of total legal remedies available to landlords (-)
	
States known as “landlord friendly” have laws that are less tolerant of tenants who fail to pay rent. Southern states which previously thrived primarily on agriculture, are commonly known for their laws that are aimed to protect landowners. As such these states (including Virginia), have laws that favor the interests of landlords with issues such as eviction, rent control, and tenant rights. Since the law, generally speaking, puts exemptions in place to favor widespread interests, we found that states with many exemptions on Fair Housing Laws and furthermore Landlord-Tenant law, are positively associated with high eviction rates and provide a minor number of legal remedies available to both tenants and landlords.

<br>

#### References
Scanlon, Edward, and Kevin Devine. "Residential mobility and youth well-being: Research, policy, and practice issues." J. Soc. & Soc. Welfare 28 (2001): 119.

 

Pribesh, Shana, and Douglas B. Downey. "Why are residential and school moves associated with poor school performance?." Demography 36.4 (1999): 521-534.

 

Kull, Melissa A., Rebekah Levine Coley, and Alicia Doyle Lynch. "The roles of instability and housing in low-income families’ residential mobility." Journal of Family and Economic Issues 37.3 (2016): 422-434.

 

Ersing, Robin L., Richard Sutphen, and Diane Nicole Loeffler. "Exploring the impact and implications of residential mobility: From the neighborhood to the school." Advances in Social Work 10.1 (2009): 1-18.

[Continue to Results Section Two](https://boya66.github.io/Richmond_website/findings/results-section-two/)
