---
title: "R Notebook"
output: html_notebook
---

```{r}
ooklafcc_df = readRDS("../data/ReConnect_Linked_07032023.RDS")
```

```{r}
library(readr)
library(proj4)
library(tigris)
library(sf)

library(dplyr)

library(readxl)
library(RPostgreSQL)
library(tidycensus)
library(data.table)
library(Matching)
library(gridExtra)
library(tidyr)

library(ggplot2)
```

```{r}
options(scipen=999)

setwd("~/Github/dspg23_broadband/broadband_analysis/")
```


```{r}
bufferzone_df = read.csv("../data/bk_in_rural_buffer.csv")
bufferzone_df = bufferzone_df[bufferzone_df$Project.ID == "IA1701-A61", ]

subscr_df = read.csv("../data/subscribers_geocoded_and_matched.csv")
subscr_df = subscr_df[subscr_df$Project.ID == "IA1701-A61", ]
```

# Get kernel smoothed Ookla data
```{r}
ookla2019 = readRDS("../data/reconnect_subscribers/ookla_data_reconnect_2019.RDS")
ookla2021 = readRDS("../data/reconnect_subscribers/ookla_data_reconnect_2021.RDS")
ookla2019 = ookla2019[ookla2019$RUSID == "IA1701-A61", ]
ookla2021 = ookla2021[ookla2021$RUSID == "IA1701-A61", ]
st_crs(ookla2019) = 4326
st_crs(ookla2019$geometry) <- 4326
st_crs(ookla2019$tile_centroid_26918) <- 4326
st_crs(ookla2021) = 4326
st_crs(ookla2021$geometry) <- 4326
st_crs(ookla2021$tile_centroid_26918) <- 4326

# ooklaKernel <- function(point, sigmasq, phi, ookla_df){
#   dist <- as.numeric( st_distance(point,ookla_df) )
#   weights <- sigmasq * exp(-(dist/phi)^2)
#   speed <- weighted.mean(ookla_df$avg_d_kbps, weights * ookla_df$devices)
#   return(speed)
# }

ooklaKernel2019 <- function(point, sigmasq, phi){
  dist <- as.numeric( st_distance(point, ookla2019) )
  weights <- sigmasq * exp(-(dist/phi)^2)
  speed <- weighted.mean(ookla2019$avg_d_kbps, weights * ookla2019$devices)
  return(speed)
}

ooklaKernel2021 <- function(point, sigmasq, phi){
  dist <- as.numeric( st_distance(point, ookla2021) )
  weights <- sigmasq * exp(-(dist/phi)^2)
  speed <- weighted.mean(ookla2021$avg_d_kbps, weights * ookla2021$devices)
  return(speed)
}
```

```{r}
bufferzone_points <- st_as_sf(bufferzone_df, coords = c("best_lng", "best_lat"), crs = 4326)

bufferzone_df$ookla_2021_avg_d_kbps <- NA
bufferzone_df$ookla_2019_avg_d_kbps <- NA
for(i in 1:nrow(bufferzone_points)){
  # bufferzone_df$ookla_2021_avg_d_kbps[i] <- ooklaKernel(bufferzone_points[i,], sigmasq=1, phi=5000, ookla2021)
  # bufferzone_df$ookla_2019_avg_d_kbps[i] <- ooklaKernel(bufferzone_points[i,], sigmasq=1, phi=5000, ookla2019)
  bufferzone_df$ookla_2021_avg_d_kbps[i] <- ooklaKernel2021(bufferzone_points[i,], sigmasq=1, phi=5000)
  bufferzone_df$ookla_2019_avg_d_kbps[i] <- ooklaKernel2019(bufferzone_points[i,], sigmasq=1, phi=5000)
  print(i)
}
```

```{r}
write.csv(bufferzone_df, "../data/iaproject/iabuffer_ookla_fitted.csv")
```


# Add GeoID 2010 and 2020
```{r}
block_2010_geometry <- readRDS("../data/reconnect_subscribers/block2010_geometry.RDS")
block_2020_geometry <- readRDS("../data/reconnect_subscribers/block2020_geometry.RDS")

selected_county_fips = read_lines("../data/tiger2020_tracts/IA1701-A61.txt")  # auto-generated by "bufferzone_implementation.ipynb"
block_2010_geometry = block_2010_geometry[substr(block_2010_geometry$GEOID10, 1, 5) %in% selected_county_fips, ]
block_2020_geometry = block_2020_geometry[substr(block_2020_geometry$GEOID20, 1, 5) %in% selected_county_fips, ]
```

```{r}
bufferzone_df = read.csv("../data/iaproject/iabuffer_ookla_fitted.csv")
```

```{r}
coord <- bufferzone_df[, c('best_lat', 'best_lng')]
coord_sf <- st_as_sf(x = coord, coords = c("best_lng","best_lat"), crs=st_crs(block_2010_geometry) )

intersect_GEOID10 <- st_intersects(coord_sf, block_2010_geometry)
coord$GEOID10 <- NA
for(i in 1:nrow(coord)){
  coord$GEOID10[i] <- block_2010_geometry$GEOID10[intersect_GEOID10[[i]][1]]
}

intersect_GEOID20 <- st_intersects(coord_sf, block_2020_geometry)
coord$GEOID20 <- NA
for(i in 1:nrow(coord)){
  coord$GEOID20[i] <- block_2020_geometry$GEOID20[intersect_GEOID20[[i]][1]]
}

bufferzone_df$GEOID10_block <- coord$GEOID10
bufferzone_df$GEOID10_blockgroup <- substr(coord$GEOID10,1,12)
bufferzone_df$GEOID10_tract <- substr(coord$GEOID10,1,11)

bufferzone_df$GEOID20_block <- coord$GEOID20
bufferzone_df$GEOID20_blockgroup <- substr(coord$GEOID20,1,12)
bufferzone_df$GEOID20_tract <- substr(coord$GEOID20,1,11)
```

```{r}
write.csv(bufferzone_df, "../data/iaproject/iabuffer_ookla_and_geoid.csv")
```

# Link FCC data
```{r}
bufferzone_df = fread("../data/iaproject/iabuffer_ookla_and_geoid.csv",
                      colClasses = c(GEOID20_block="character", GEOID10_block="character"))

fcc2019 <- fread("../data/reconnect_subscribers/fbd_us_without_satellite_dec2019_v1.csv",
                 colClasses = c(BlockCode="character"))
fcc2020 <- fread("../data/reconnect_subscribers/fbd_us_without_satellite_dec2020_v1.csv",
                 colClasses = c(BlockCode="character"))
fcc2021 <- fread("../data/reconnect_subscribers/fbd_us_without_satellite_dec2021_v1.csv",
                 colClasses = c(BlockCode="character"))
```

```{r}
fcc2019_block <- fcc2019 %>% filter(BlockCode %in% bufferzone_df$GEOID10_block) %>%
  group_by(BlockCode) %>% summarize(
    FCC_providers2019=n(),
    FCC_MaxAdDown2019=max(MaxAdDown,na.rm=TRUE),
    FCC_MaxAdUp2019=max(MaxAdUp,na.rm=TRUE),
    FCC_MedAdDown2019=median(MaxAdDown, na.rm=TRUE),
    FCC_AvgAdDown2019=mean(MaxAdDown, na.rm=TRUE)
  )

fcc2020_block <- fcc2020 %>% filter(BlockCode %in% bufferzone_df$GEOID10_block) %>%
  group_by(BlockCode) %>% summarize(
    FCC_providers2020=n(),
    FCC_MaxAdDown2020=max(MaxAdDown,na.rm=TRUE),
    FCC_MaxAdUp2020=max(MaxAdUp,na.rm=TRUE),
    FCC_MedAdDown2020=median(MaxAdDown, na.rm=TRUE),
    FCC_AvgAdDown2020=mean(MaxAdDown, na.rm=TRUE)
  )

fcc2021_block <- fcc2021 %>% filter(BlockCode %in% bufferzone_df$GEOID20_block) %>%
  group_by(BlockCode) %>% summarize(
    FCC_providers2021=n(),
    FCC_MaxAdDown2021=max(MaxAdDown,na.rm=TRUE),
    FCC_MaxAdUp2021=max(MaxAdUp,na.rm=TRUE),
    FCC_MedAdDown2021=median(MaxAdDown, na.rm=TRUE),
    FCC_AvgAdDown2021=mean(MaxAdDown, na.rm=TRUE)
  )

```

```{r}
bufferzone_df2 <- bufferzone_df %>%
  left_join(fcc2019_block, by=c('GEOID10_block'='BlockCode')) %>%
  left_join(fcc2020_block, by=c('GEOID10_block'='BlockCode')) %>%
  left_join(fcc2021_block, by=c('GEOID20_block'='BlockCode'))
```

```{r}
write.csv(bufferzone_df2, "../data/iaproject/iabuffer_linked_all.csv")
```