---
title: "04_embedding"
author: "Crystal"
date: "7/27/2021"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r message=FALSE, warning=FALSE, paged.print=FALSE}
library(readr)
library(dplyr)
library(tidyr)
library(mosaic)
library("stringr")
library("tidyr")
library("dplyr")
library("readr")
library("tidyverse")
library("DT")
library("RPostgreSQL")
library(ggforce)

library(gridExtra)
```

```{r message=FALSE, warning=FALSE, paged.print=FALSE}
setwd("/home/zz3hs/git/dspg21oss/data/dspg21oss/")
embeddings <- read_rds("/home/zz3hs/git/dspg21oss/shiny/data_shiny/classified_repos_embeddings.rds")

#label <- read_csv("github_repos_157k_label.csv")
label_true <- read_rds("/home/zz3hs/git/dspg21oss/shiny/data_shiny/classified_repos_labelled.rds")

#corpus_label <- read_csv("oss_software_labelled.csv")
```

# Corpus (ground truth repos) Embedding in 2d 
```{r}
ids = colnames(corpus_label)
ids

corpus_ids = c()
for (i in (1:length(ids))){
  id = ids[i]
  if (grepl("label", id)){
    corpus_ids <- append(corpus_ids, id) 
  }
}

corpus_ids
corpus_label_true <- corpus_label%>%
  select(slug, corpus_ids)%>%
  gather(software_type, IS_TRUE,-slug)%>%
  mutate(IS_TRUE= ifelse(IS_TRUE >0, T, F))%>%
  right_join(embeddings, by = "slug")%>%
  filter(!is.na(IS_TRUE))


ggplot(filter(corpus_label_true, software_type %in% c("blockchain_label", "database_label")), aes(x = x, y = y)) + 
  geom_point()  + aes(colour = software_type) + 
  theme(legend.position = "right") + 
  labs(title = "First two principal components, ground truth")+
  geom_mark_circle(aes(color = software_type))

```

# Classified Repos' Embeddings 
```{r}
#tm_ids =  c("app_blockchain_tm", "app_database_tm", "prog_clang_tm","prog_java_tm", "prog_javascript_tm", "prog_php_tm", "prog_python_tm", "topics_ai_tm", "topics_dataviz_tm")

#bert_ids = c("topics_ai_bert", "app_blockchain_bert", "prog_clang_bert","app_database_bert", "topics_dataviz_bert", "prog_java_bert", "prog_javascript_bert", "prog_php_bert", "prog_python_bert")

table(label_true$software_type)

bert_embeddings_label = left_join(label_true, embeddings, by = "slug")


p1 <- ggplot(
            filter(bert_embeddings_label, software_type %in% c("app_blockchain", "topics_dataviz")), 
            aes(x=x, 
                y=y,
                slug = slug,
                description = description,
                software_type = software_type,
                stars= stars)
            ) + 
  geom_point()  + 
  aes(colour = software_type) + 
  theme(legend.position = "top") + 
  labs(title = "Embeddings of repos classified as Blockchain and Data Visualization", 
       subtitle = "1st + 2nd principal components")+
  theme_minimal()

ply1 <- ggplotly(p1, tooltip = c("slug", "software_type", "description", "stars"))


p2 <-ggplot(
            filter(bert_embeddings_label, software_type %in% c("app_blockchain", "topics_dataviz")), 
            aes(x=y, 
                y=z,
                slug = slug,
                description = description,
                software_type = software_type,
                stars= stars)
            ) + 
  geom_point()  + 
  aes(colour = software_type) + 
  theme(legend.position = "top") + 
  labs(title = "Embeddings of repos classified as Blockchain and Data Visualization", 
       subtitle = "2nd + 3rd principal components")+
  theme_minimal()

ply2 <- ggplotly(p2, tooltip = c("slug", "software_type", "description", "stars"))
plys = subplot(ply1, ply2, nrows=1)

plys
```


## 3d plot using rgl
```{r}
library(akima)

library(rgl)
x = embeddings_label$x
y = embeddings_label$y
z = embeddings_label$z
s = interp(x,y,z, duplicate =F)

#surface3d(s$x,s$y,s$z)
```

## 3d plot using scatterplot3d
```{r}
library("scatterplot3d") 
table(embeddings_label$software_type)

colors_rgb <- c("#232d4b","#2c4f6b","#0e879c",
            "#60999a","#d1e0bf","#d9e12b",
            "#e6ce3a","#e6a01d","#e57200")
colors <- colors_rgb[as.numeric(embeddings_label$software_type)]


scatterplot3d(x=embeddings_label$x, y=embeddings_label$y, z=embeddings_label$z, color = colors)
```

#How many software types a repo is classified (Term matching VS BERT)
```{r}
slug_freq_true_bert =label_true%>%
  group_by(slug)%>%
  summarize(N = sum(bert))

ggplot(slug_freq_true_bert, aes(x = N)) + 
  geom_histogram(binwidth = 0.54) + 
  labs(title = "How many software types a repo is classified") 

slug_freq_true_tm =label_true%>%
  group_by(slug)%>%
  summarize(N = sum(term_matching))

ggplot(slug_freq_true_tm, aes(x = N)) + 
  geom_histogram(binwidth = 0.54) + 
  labs(title = "How many software types a repo is classified") 
```

# Software type (Blockchain)'s subtype embedding in 2d --- corpus
```{r}
corpus_label_true$description <- tolower(corpus_label_true$description)
blockchain_corpus = corpus_label_true%>%
  filter(software_type == "blockchain_label")%>%
  mutate(subtype_polkadot = ifelse(grepl("polkadot",description), T,F))%>% 
  mutate(subtype_uniswap = ifelse(grepl("uniswap",description), T,F))%>%   
  mutate(subtype_ethereum = ifelse(grepl("ethereum",description), T,F))%>% 
    mutate(subtype_bitcoin = ifelse(grepl("bitcoin",description), T,F))%>%
    mutate(subtype_crypocurrency = ifelse(grepl("crypocurrency",description), T,F))%>%
    mutate(subtype_blockchain = ifelse(grepl("blockchain",description), T,F))%>%
  select(-software_type, -IS_TRUE)%>%
  gather(subtype, IS_TRUE,-c(slug, description, x,y,z))

blockchain_corpus%>%
  filter(IS_TRUE == T)%>%
  group_by(subtype)%>%
  summarize(N=n())

blockchain_corpus%>%
  filter(IS_TRUE==T)%>%
  filter(subtype %in% c("subtype_polkadot", "subtype_ethereum","subtype_uniswap","subtype_bitcoin"))%>%
  ggplot(aes(x = x, y = y)) + 
  geom_point()  +
  aes(colour = subtype) + 
  theme(legend.position = "right") + 
  labs(title = "First two principal components")

```


```{r}
bert_embeddings_label$description.x <- tolower(bert_embeddings_label$description.x)
table(bert_embeddings_label$software_type)

blockchain_all = bert_embeddings_label%>%
  select(-description.y)%>%
  filter(software_type == "app_blockchain")%>%
  mutate(subtype_polkadot = ifelse(grepl("polkadot",description.x), T,F))%>% 
  mutate(subtype_uniswap = ifelse(grepl("uniswap",description.x), T,F))%>%   
  mutate(subtype_ethereum = ifelse(grepl("ethereum",description.x), T,F))%>% 
    mutate(subtype_bitcoin = ifelse(grepl("bitcoin",description.x), T,F))%>%
    mutate(subtype_crypocurrency = ifelse(grepl("crypocurrency",description.x), T,F))%>%
    mutate(subtype_blockchain = ifelse(grepl("blockchain",description.x), T,F))%>%
  select(-software_type,  -language, -topics, -commits, -forks, -stars, -watchers, -bert, -term_matching)%>%
  gather(subtype, IS_TRUE,-c(slug, description.x, x,y,z))

blockchain_all%>%
  filter(IS_TRUE == T)%>%
  group_by(subtype)%>%
  summarize(N=n())

blockchain_all%>%
  filter(IS_TRUE==T)%>%
  filter(subtype %in% c("subtype_polkadot", "subtype_ethereum","subtype_uniswap","subtype_bitcoin", "subtype_blockchain"))%>%
  ggplot(aes(x = x, y = y)) + 
  geom_point()  +
  aes(colour = subtype) + 
  theme(legend.position = "right") + 
  labs(title = "First two principal components")

```
