---
title: "Job Zone Imputations (2010)"
author: "Sarah McDonald"
date: "7/1/2020"
output: html_document
#output: md_document
#always_allow_html: true
---

Load packages and BGT 2010 data:
```{r, warning=F, message = F}
library(dplyr)
library(tidyr)

source("job_zones.R")

conn <- RPostgreSQL::dbConnect(drv = RPostgreSQL::PostgreSQL(),
                               dbname = "sdad",
                               host = "postgis1",
                               port = 5432,
                               user = Sys.getenv(x = "DB_USR"),
                               password = Sys.getenv(x = "DB_PWD"))

zones <- RPostgreSQL::dbGetQuery(
  conn = conn, 
  statement = "SELECT * FROM onet.job_zones")

# retrieves onet code
bgt <- RPostgreSQL::dbGetQuery(
  conn = conn, 
  statement = "SELECT A.id, A.minedu, A.soc, B.onet
  FROM bgt_job.jolts_comparison_2010 A
  JOIN bgt_job.main B
  ON A.id = B.id")

```


Match Job Zone to each BGT job-ad:
```{r}
bgt$job_zone<- zones$job_zone[match(bgt$onet, zones$onetsoc_code)]
```


Print non-matched O*Net codes: 
```{r}
nonMatch <- bgt%>%filter(is.na(onet) == FALSE & is.na(job_zone)==TRUE) %>% select(onet,soc) %>% unique()
print(unique(nonMatch$onet))
```

Share of BGT Job-Ads with complete Job Zone and/or Minedu observations:
```{r}
share <- data.frame("Job Zone and Minedu" = nrow(bgt %>% filter(is.na(job_zone)==FALSE & is.na(minedu)==FALSE))/nrow(bgt),
                    "Minedu Only" = nrow(bgt %>% filter(is.na(job_zone)==TRUE & is.na(minedu)==FALSE))/nrow(bgt),
                    "Job Zone Only" = nrow(bgt %>% filter(is.na(job_zone)==FALSE & is.na(minedu)==TRUE))/nrow(bgt),
                    "Neither Job Zone nor Minedu" = nrow(bgt %>% filter(is.na(job_zone)==TRUE & is.na(minedu)==TRUE))/nrow(bgt)
)


job_zones(2010:2019)

knitr::kable(share)
```

Jobs Zone and Minedu Combination Counts:
```{r, message = F, warning= F}
tbl <- bgt %>% filter(is.na(job_zone)==FALSE & is.na(minedu)==FALSE) %>% 
  select(job_zone, minedu, id) %>%
  group_by(job_zone, minedu) %>%
  summarise(Count.of.IDs = n())

knitr::kable(counts_wide)
```








