---
title: "Exploring Temperature & Pulse Oximetry"
author: "Chase Dawson"
date: "7/6/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(vroom)
library(here)

# load the data
ems <- vroom::vroom(here("data", "original", "2020 UVA Project County Bulk Export_Export.csv"),
                        col_types = col_spec) %>%
  rename_with(~tolower(gsub(r"( +\(.*)", "", .x))) %>% # remove code after variable names
  rename_with(~gsub(r"( )", "_", .x)) %>%  # change periods to underscores
  select(-all_of(drop_cols))
```

## Temperature
Number of incidents with no temperature data:
```{r}
ems %>%
  filter(is.na(patient_initial_body_temperature_in_fahrenheit) & is.na(patient_last_body_temperature_in_fahrenheit)) %>%
  count()
```

```{r cars}
summary(cars)
```

## Pulse Oximetry

You can also embed plots, for example:

```{r pressure, echo=FALSE}
plot(pressure)
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
