---
title: "ACS test"
author: "Morgan Klutzke"
date: "7/13/2020"
output: html_document
---

```{r}
library(tidycensus)
library(maps)
library(data.table)
library(magrittr)
library(maditr)
library(dplyr)
library(stringr)
library(ggplot2)
library(tigris)

# API key here
census_api_key(Sys.getenv("CENSUS_API_KEY"))

# get a reference of variable IDs for 2018 ACS
v18 <- load_variables(2018, "acs5", cache = TRUE)
```

```{r}
# list variables we want for each census tract
acs_vars <- c("B25075_001", "B25075_002", "B25075_003", "B25075_004", "B25075_005", "B25075_006", "B25075_007", "B25075_008", "B25075_009", "B25075_010", "B25075_011", "B25075_012", "B25075_013", "B25075_014", "B25075_015", "B25075_016", "B25075_017", "B25075_018", "B25075_019", "B25075_020", "B25075_021", "B25075_022", "B25075_023", "B25075_024", "B25075_025", "B25075_026", "B25075_027", # value
              "B25077_001", # median value
              "B25001_001", # housing units
              #"B25002_001", "B25002_002", "B25002_003",# occupancy status
              #"B25024_001", "B25024_002", "B25024_003", "B25024_004", "B25024_005", "B25024_006", "B25024_007", "B25024_008", "B25024_009", "B25024_010", "B25024_011", # number of units
              #"B25041_001", "B25041_002", "B25041_003", "B25041_004", "B25041_005", "B25041_006", "B25041_007", # number of bedrooms
              "B25034_001", "B25034_002", "B25034_003", "B25034_004", "B25034_005", "B25034_006", "B25034_007", "B25034_008", "B25034_009", "B25034_010", "B25034_011", # year built
              "B25035_001" # median year built
)

# function to clean raw ACS data
# changes to a tidy format that works well with dplyr & ggplot
# adds descriptive variable names
# calculates and stores 90% confidence interval boundaries
get_estimates_tidy <- function(acs_data) {
  acs_data <- as.data.table(acs_data) %>%
    dt_mutate(NAME = str_extract(NAME, "(?<=Census Tract )[0-9.]*")) %>%
    rename(census_tract = NAME) %>%
    dt_mutate(variable = str_replace(variable, "B25077_001", "value median")) %>%
    dt_mutate(variable = str_replace(variable, "B25075_001", "value total")) %>%
    dt_mutate(variable = str_replace(variable, "B25075_002", "value <10")) %>%
    dt_mutate(variable = str_replace(variable, "B25075_003", "value 10-15")) %>%
    dt_mutate(variable = str_replace(variable, "B25075_004", "value 15-20")) %>%
    dt_mutate(variable = str_replace(variable, "B25075_005", "value 20-25")) %>%
    dt_mutate(variable = str_replace(variable, "B25075_006", "value 25-30")) %>%
    dt_mutate(variable = str_replace(variable, "B25075_007", "value 30-35")) %>%
    dt_mutate(variable = str_replace(variable, "B25075_008", "value 35-40")) %>%
    dt_mutate(variable = str_replace(variable, "B25075_009", "value 40-50")) %>%
    dt_mutate(variable = str_replace(variable, "B25075_010", "value 50-60")) %>%
    dt_mutate(variable = str_replace(variable, "B25075_011", "value 60-70")) %>%
    dt_mutate(variable = str_replace(variable, "B25075_012", "value 70-80")) %>%
    dt_mutate(variable = str_replace(variable, "B25075_013", "value 80-90")) %>%
    dt_mutate(variable = str_replace(variable, "B25075_014", "value 90-100")) %>%
    dt_mutate(variable = str_replace(variable, "B25075_015", "value 100-125")) %>%
    dt_mutate(variable = str_replace(variable, "B25075_016", "value 125-150")) %>%
    dt_mutate(variable = str_replace(variable, "B25075_017", "value 150-175")) %>%
    dt_mutate(variable = str_replace(variable, "B25075_018", "value 175-200")) %>%
    dt_mutate(variable = str_replace(variable, "B25075_019", "value 200-250")) %>%
    dt_mutate(variable = str_replace(variable, "B25075_020", "value 250-300")) %>%
    dt_mutate(variable = str_replace(variable, "B25075_021", "value 300-400")) %>%
    dt_mutate(variable = str_replace(variable, "B25075_022", "value 400-500")) %>%
    dt_mutate(variable = str_replace(variable, "B25075_023", "value 500-750")) %>%
    dt_mutate(variable = str_replace(variable, "B25075_024", "value 750-1000")) %>%
    dt_mutate(variable = str_replace(variable, "B25075_025", "value 1000-1500")) %>%
    dt_mutate(variable = str_replace(variable, "B25075_026", "value 1500-2000")) %>%
    dt_mutate(variable = str_replace(variable, "B25075_027", "value >2000")) %>%
    dt_mutate(variable = str_replace(variable, "B25035_001", "yrbuilt median")) %>%
    dt_mutate(variable = str_replace(variable, "B25034_001", "yrbuilt total")) %>%
    dt_mutate(variable = str_replace(variable, "B25034_002", "yrbuilt 2014-later")) %>%
    dt_mutate(variable = str_replace(variable, "B25034_003", "yrbuilt 2010-2013")) %>%
    dt_mutate(variable = str_replace(variable, "B25034_004", "yrbuilt 2000-2009")) %>%
    dt_mutate(variable = str_replace(variable, "B25034_005", "yrbuilt 1990-1999")) %>%
    dt_mutate(variable = str_replace(variable, "B25034_006", "yrbuilt 1980-1989")) %>%
    dt_mutate(variable = str_replace(variable, "B25034_007", "yrbuilt 1970-1979")) %>%
    dt_mutate(variable = str_replace(variable, "B25034_008", "yrbuilt 1960-1969")) %>%
    dt_mutate(variable = str_replace(variable, "B25034_009", "yrbuilt 1950-1959")) %>%
    dt_mutate(variable = str_replace(variable, "B25034_010", "yrbuilt 1940-1949")) %>%
    dt_mutate(variable = str_replace(variable, "B25034_011", "yrbuilt earlier-1939")) %>%
    #dt_mutate(variable = str_replace(variable, "B25041_001", "bedrooms total")) %>%
    #dt_mutate(variable = str_replace(variable, "B25041_002", "bedrooms none")) %>%
    #dt_mutate(variable = str_replace(variable, "B25041_003", "bedrooms 1")) %>%
    #dt_mutate(variable = str_replace(variable, "B25041_004", "bedrooms 2")) %>%
    #dt_mutate(variable = str_replace(variable, "B25041_005", "bedrooms 3")) %>%
    #dt_mutate(variable = str_replace(variable, "B25041_006", "bedrooms 4")) %>%
    #dt_mutate(variable = str_replace(variable, "B25041_007", "bedrooms 5+")) %>%
    dt_mutate(variable = str_replace(variable, "B25001_001", "housing_units total")) %>%
    #dt_mutate(variable = str_replace(variable, "B25002_001", "occupancy_status total")) %>%
    #dt_mutate(variable = str_replace(variable, "B25002_002", "occupancy_status occupied")) %>%
    #dt_mutate(variable = str_replace(variable, "B25002_003", "occupancy_status vacant")) %>%
    #dt_mutate(variable = str_replace(variable, "B25024_001", "unit_no total")) %>%
    #dt_mutate(variable = str_replace(variable, "B25024_002", "unit_no 1 detached")) %>%
    #dt_mutate(variable = str_replace(variable, "B25024_003", "unit_no 1 attached")) %>%
    #dt_mutate(variable = str_replace(variable, "B25024_004", "unit_no 2")) %>%
    #dt_mutate(variable = str_replace(variable, "B25024_005", "unit_no 3-4")) %>%
    #dt_mutate(variable = str_replace(variable, "B25024_006", "unit_no 5-9")) %>%
    #dt_mutate(variable = str_replace(variable, "B25024_007", "unit_no 10-19")) %>%
    #dt_mutate(variable = str_replace(variable, "B25024_008", "unit_no 20-49")) %>%
    #dt_mutate(variable = str_replace(variable, "B25024_009", "unit_no 50+")) %>%
    #dt_mutate(variable = str_replace(variable, "B25024_010", "unit_no mobile")) %>%
    #dt_mutate(variable = str_replace(variable, "B25024_011", "unit_no other")) %>%
    dt_mutate(value = str_extract(variable, "(?<=\\s).+")) %>%
    dt_mutate(variable = str_extract(variable, "[a-z_]+")) %>%
    setcolorder(c("GEOID", "census_tract", "variable", "value", "estimate", "moe")) %>%
    dt_mutate(lower_ci = estimate - moe) %>%
    dt_mutate(upper_ci = estimate + moe) %>%
    dt_mutate(lower_ci = if_else(condition = lower_ci < 0, true = 0, false = lower_ci))
}

# get data for fairfax county
ffx <- get_acs(geography = "tract", state = 51, county = 059,
               variables = acs_vars,
               year = 2018, survey = "acs5",
               cache_table = TRUE)
ffx_estimates <- get_estimates_tidy(ffx)

# get data for new kent country
nk <- get_acs(geography = "tract", state = 51, county = 127,
              variables = acs_vars,
              year = 2018, survey = "acs5",
              cache_table = TRUE)
nk_estimates <- get_estimates_tidy(nk)
```


```{r, fig.height=7}
get_values <- function(estimates) {
  values <- estimates %>%
    filter(variable == "value") %>%
    filter(value != "median" & value != "total") %>%
    group_by(value) %>%
    summarise(n = sum(estimate), lower_sum = sum(lower_ci), upper_sum = sum(upper_ci)) %>%
    dt_mutate(value = factor(value, levels = c("<10", "10-15", "15-20", "20-25", "25-30", "30-35", "35-40", "40-50", "50-60", "60-70", "70-80", "80-90", "90-100", "100-125", "125-150", "150-175", "175-200", "200-250", "250-300", "300-400", "400-500", "500-750", "750-1000", "1000-1500", "1500-2000", ">2000"))) %>%
    arrange(value)
}

nk_values <- get_values(nk_estimates)
ffx_values <- get_values(ffx_estimates)

ggplot(nk_values) + geom_col(aes(x = value, y = n)) + geom_errorbar(aes(x = value, ymin = lower_sum, ymax = upper_sum)) + theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1)) + labs(x = "value (thousands of $)", title = "New Kent")

ggplot(ffx_values) + geom_col(aes(x = value, y = n)) + geom_errorbar(aes(x = value, ymin = lower_sum, ymax = upper_sum)) + theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1)) + labs(x = "value (thousands of $)", title = "Fairfax")
```

```{r, fig.height=7}
get_yrbuilt <- function(estimates) {
  yrbuilt <- estimates %>%
    filter(variable == "yrbuilt") %>%
    filter(value != "median" & value != "total") %>%
    group_by(value) %>%
    summarise(n = sum(estimate), lower_sum = sum(lower_ci), upper_sum = sum(upper_ci)) %>%
    dt_mutate(value = factor(value, levels = c("earlier-1939", "1940-1949", "1950-1959", "1960-1969", "1970-1979", "1980-1989", "1990-1999", "2000-2009", "2010-2013", "2014-later"))) %>%
    arrange(value)
}

nk_yrbuilt <- get_yrbuilt(nk_estimates)
ffx_yrbuilt <- get_yrbuilt(ffx_estimates)

ggplot(nk_yrbuilt) + geom_col(aes(x = value, y = n)) + geom_errorbar(aes(x = value, ymin = lower_sum, ymax = upper_sum)) + theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1)) + labs(x = "year built", title = "New Kent")

ggplot(ffx_yrbuilt) + geom_col(aes(x = value, y = n)) + geom_errorbar(aes(x = value, ymin = lower_sum, ymax = upper_sum)) + theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1)) + labs(x = "year built", title = "Fairfax")
```

Get corelogic data

```{r}
get_db_conn <-
  function(db_name = "sdad",
           db_host = "postgis1",
           db_port = "5432",
           db_user = Sys.getenv("db_usr"), # requires you to setup environmental vars
           db_pass = Sys.getenv("db_pwd")) {
    RPostgreSQL::dbConnect(
      drv = RPostgreSQL::PostgreSQL(),
      dbname = db_name,
      host = db_host,
      port = db_port,
      user = db_user,
      password = db_pass
    )
  }

con <- get_db_conn()

# get corelogic data for new kent county (tax_year is 2018 for all of new kent in this data, and assessed_total_value is always the same as market_total_value)
cl_nk <- DBI::dbGetQuery(con, statement = paste(
  "SELECT census_tract, assessed_total_value, year_built",
  "FROM corelogic_sdad.tax_hist_2_51",
  "WHERE fips_code='51127'"))

DBI::dbDisconnect(con)

# only VA FIPS
va_tracts <- tracts(state = '51', year = 2018) %>% as.data.frame()

# get regex of all census tract codes
regex_census_tract <- paste0(va_tracts$TRACTCE, collapse = "|")

cl_nk<- cl_nk %>% 
  mutate(ct_detect = str_extract_all(census_tract, pattern = regex_census_tract)) %>%
  mutate(ct_detect = as.character(ct_detect))

#323 observations are missing census tracts in new kent
sum(is.na(cl_nk$ct_detect))
```


```{r}
# at first has 375,410 observations

#filter(ffx_2018, assessed_total_value != market_total_value)
# market total value is always equal to assessed total value



cl_ffx_values <- ffx_2018 %>%
  select(assessed_total_value) %>%
  filter(!is.na(assessed_total_value)) %>%
  transmute(value = assessed_total_value) %>%
  dt_mutate(value = if_else(as.numeric(value) < 10000, "10", value)) %>%
  dt_mutate(value = if_else(as.numeric(value) < 15000 & as.numeric(value) >= 10000, "15", value)) %>%
  dt_mutate(value = if_else(as.numeric(value) < 20000 & as.numeric(value) >= 15000, "20", value)) %>%
  dt_mutate(value = if_else(as.numeric(value) < 25000 & as.numeric(value) >= 20000, "25", value)) %>%
  dt_mutate(value = if_else(as.numeric(value) < 30000 & as.numeric(value) >= 25000, "30", value)) %>%
  dt_mutate(value = if_else(as.numeric(value) < 35000 & as.numeric(value) >= 30000, "35", value)) %>%
  dt_mutate(value = if_else(as.numeric(value) < 40000 & as.numeric(value) >= 35000, "40", value)) %>%
  dt_mutate(value = if_else(as.numeric(value) < 50000 & as.numeric(value) >= 40000, "50", value)) %>%
  dt_mutate(value = if_else(as.numeric(value) < 60000 & as.numeric(value) >= 50000, "60", value)) %>%
  dt_mutate(value = if_else(as.numeric(value) < 70000 & as.numeric(value) >= 60000, "70", value)) %>%
  dt_mutate(value = if_else(as.numeric(value) < 80000 & as.numeric(value) >= 70000, "80", value)) %>%
  dt_mutate(value = if_else(as.numeric(value) < 90000 & as.numeric(value) >= 80000, "90", value)) %>%
  dt_mutate(value = if_else(as.numeric(value) < 100000 & as.numeric(value) >= 90000, "100", value)) %>%
  dt_mutate(value = if_else(as.numeric(value) < 125000 & as.numeric(value) >= 100000, "125", value)) %>%
  dt_mutate(value = if_else(as.numeric(value) < 150000 & as.numeric(value) >= 125000, "150", value)) %>%
  dt_mutate(value = if_else(as.numeric(value) < 175000 & as.numeric(value) >= 150000, "175", value)) %>%
  dt_mutate(value = if_else(as.numeric(value) < 200000 & as.numeric(value) >= 175000, "200", value)) %>%
  dt_mutate(value = if_else(as.numeric(value) < 250000 & as.numeric(value) >= 200000, "250", value)) %>%
  dt_mutate(value = if_else(as.numeric(value) < 300000 & as.numeric(value) >= 250000, "300", value)) %>%
  dt_mutate(value = if_else(as.numeric(value) < 400000 & as.numeric(value) >= 300000, "400", value)) %>%
  dt_mutate(value = if_else(as.numeric(value) < 500000 & as.numeric(value) >= 400000, "500", value)) %>%
  dt_mutate(value = if_else(as.numeric(value) < 750000 & as.numeric(value) >= 500000, "750", value)) %>%
  dt_mutate(value = if_else(as.numeric(value) < 1000000 & as.numeric(value) >= 750000, "1000", value)) %>%
  dt_mutate(value = if_else(as.numeric(value) < 1500000 & as.numeric(value) >= 1000000, "1500", value)) %>%
  dt_mutate(value = if_else(as.numeric(value) < 2000000 & as.numeric(value) >= 1500000, "2000", value)) %>%
  dt_mutate(value = if_else(as.numeric(value) >= 2000000, ">2000", value)) %>%
  dt_mutate(value = if_else(value == "10", "<10", value)) %>%
  dt_mutate(value = if_else(value == "15", "10-15", value)) %>%
  dt_mutate(value = if_else(value == "20", "15-20", value)) %>%
  dt_mutate(value = if_else(value == "25", "20-25", value)) %>%
  dt_mutate(value = if_else(value == "30", "25-30", value)) %>%
  dt_mutate(value = if_else(value == "35", "30-35", value)) %>%
  dt_mutate(value = if_else(value == "40", "35-40", value)) %>%
  dt_mutate(value = if_else(value == "50", "40-50", value)) %>%
  dt_mutate(value = if_else(value == "60", "50-60", value)) %>%
  dt_mutate(value = if_else(value == "70", "60-70", value)) %>%
  dt_mutate(value = if_else(value == "80", "70-80", value)) %>%
  dt_mutate(value = if_else(value == "90", "80-90", value)) %>%
  dt_mutate(value = if_else(value == "100", "90-100", value)) %>%
  dt_mutate(value = if_else(value == "125", "100-125", value)) %>%
  dt_mutate(value = if_else(value == "150", "125-150", value)) %>%
  dt_mutate(value = if_else(value == "175", "150-175", value)) %>%
  dt_mutate(value = if_else(value == "200", "175-200", value)) %>%
  dt_mutate(value = if_else(value == "250", "200-250", value)) %>%
  dt_mutate(value = if_else(value == "300", "250-300", value)) %>%
  dt_mutate(value = if_else(value == "400", "300-400", value)) %>%
  dt_mutate(value = if_else(value == "500", "400-500", value)) %>%
  dt_mutate(value = if_else(value == "750", "500-750", value)) %>%
  dt_mutate(value = if_else(value == "1000", "750-1000", value)) %>%
  dt_mutate(value = if_else(value == "1500", "1000-1500", value)) %>%
  dt_mutate(value = if_else(value == "2000", "1500-2000", value)) %>%
  group_by(value) %>%
  summarise(n = n()) %>%
  dt_mutate(value = factor(value, levels = c("<10", "10-15", "15-20", "20-25", "25-30", "30-35", "35-40", "40-50", "50-60", "60-70", "70-80", "80-90", "90-100", "100-125", "125-150", "150-175", "175-200", "200-250", "250-300", "300-400", "400-500", "500-750", "750-1000", "1000-1500", "1500-2000", ">2000"))) %>%
  arrange(value)

ggplot(cl_ffx_values) + geom_col(aes(x = value, y = n)) + theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1)) + labs(x = "value (thousands of $)", title = "Fairfax (CoreLogic)")
```

