---
title: "BGT Job Ad IDs"
author: "Sarah McDonald"
date: "6/27/2020"
output: md_document
always_allow_html: true
---

```{r, warning=F, message = F, echo = F}
library(tidyr)

conn <- RPostgreSQL::dbConnect(drv = RPostgreSQL::PostgreSQL(),
                               dbname = "sdad",
                               host = "postgis1",
                               port = 5432,
                               user = Sys.getenv(x = "DB_USR"),
                               password = Sys.getenv(x = "DB_PWD"))
#RPostgreSQL::dbDisconnect(conn)
```

```{r}
freq_table <- data.frame(Var1 = character(0), Freq = numeric(0), year = numeric(0))
years <- 2010:2019

for(y in years){
  
  tbl <- RPostgreSQL::dbGetQuery(
      conn = conn, 
      statement = paste("SELECT id FROM bgt_job.jolts_comparison_", y, sep = ""))
    
  freq <- as.data.frame(table(nchar(tbl$id)))

  freq$year <- y

  freq_table <- rbind(freq_table, freq)
}

freq_table$Var1 <- as.factor(freq_table$Var1)
freq_table_wide <- reshape(freq_table, idvar = "year", timevar = "Var1", direction = "wide")
freq_table_wide <- freq_table_wide[c(1, 10, 11, 12, 6,2, 7,8, 3,4,9,5)]
freq_table_wide[is.na(freq_table_wide)] <- 0
```


Count of IDs by Number of Characters
```{r}
knitr::kable(freq_table_wide, row.names = FALSE)
```








