---
title: "Visualizing fitness for use"
author: "Morgan Klutzke"
date: "7/28/2020"
output: html_document
---

```{r}
library(maps)
library(data.table)
library(magrittr)
library(maditr)
library(dplyr)
library(stringr)
library(ggplot2)
library(leaflet)
library(readr)
library(tigris)
library(tidyr)
```

```{r}
ffu_va <- read_csv("~/git/dspg20broadbandERS/data/acs-cl-joined/ffu_va.csv")
#nrow(filter(ffu_va, is.na(ffu_housing_units_total))) #559 tracts with no data
ruca <- read_csv("~/git/dspg20broadbandERS/data/census-geographies/RUCA.csv")

ffu_va <- ffu_va %>% 
  dt_mutate(GEOID = as.character(GEOID)) %>%
  left_join(ruca)

va_tracts <- tracts(state = '51', year = 2018)
ffu_merged <- geo_join(va_tracts, ffu_va, "GEOID", "GEOID")
```

```{r fig.height=7, fig.width=12}
# making boxplots
ffu_va_longer <- ffu_va %>%
  pivot_longer(-GEOID, names_to = "variable", values_to = "ffu") %>%
  drop_na()

ffu_va_value <- ffu_va_longer %>% filter(str_detect(variable, "value"))
ffu_va_yrbuilt <- ffu_va_longer %>% filter(str_detect(variable, "yrbuilt"))
ffu_va_housing <- ffu_va_longer %>% filter(str_detect(variable, "housing|occupancy"))

ggplot(ffu_va_value, aes(ffu, variable)) + geom_boxplot() + geom_vline(xintercept = -1, linetype = "dashed", color = "red") + geom_vline(xintercept = 1, linetype = "dashed", color = "red")
ggplot(ffu_va_yrbuilt, aes(ffu, variable)) + geom_boxplot() + geom_vline(xintercept = -1, linetype = "dashed", color = "red") + geom_vline(xintercept = 1, linetype = "dashed", color = "red")
ggplot(ffu_va_housing, aes(ffu, variable)) + geom_boxplot() + geom_vline(xintercept = -1, linetype = "dashed", color = "red") + geom_vline(xintercept = 1, linetype = "dashed", color = "red")
```

```{r}
plot(density(na.omit(ffu_va$ffu_housing_units_total)))
quantile(na.omit(ffu_va$ffu_housing_units_total))
quantile(na.omit(ffu_va$ffu_housing_units_total), probs = seq(0, 1, length.out = 11))
```

```{r}
#range(na.omit(ffu_va$ffu_housing_units_total)) # -98 to 46
bins <- c(-100, -10, -5, -2, -1, 1, 2, 5, 10, 100)
pal <- colorBin(palette = "BrBG", domain = ffu_merged$ffu_housing_units_total, bins = bins)
#popup <- paste0("GEOID: ", ffu_merged$GEOID, "<br>", "Fitness for Use: ", round(ffu_merged$ffu_housing_units_total, 2))
label <- paste(ffu_merged$County, "<br/>", 
               "RUCA Code: ", ffu_merged$RUCA1, "<br/>", 
               "Fitness for Use: ", ifelse(test = is.na(ffu_merged$ffu_housing_units_total), 
                                           yes = "no data", 
                                           no = round(ffu_merged$ffu_housing_units_total, 2)), 
               sep = "") %>%
  lapply(htmltools::HTML)

ffu_map <- leaflet() %>%
  addProviderTiles(providers$CartoDB.Positron) %>%
  addPolygons(data = ffu_merged,
              fillColor = ~pal(ffu_housing_units_total),
              color = "#808080",
              fillOpacity = 0.7,
              weight = 1,
              smoothFactor = 0.2,
              label = label) %>%
  addLegend(pal = pal,
            values = ffu_merged$ffu_housing_units_total,
            position = "topleft",
            title = "Fitness for Use")

ffu_map
```

