---
title: "08_06_2023Armor"
output: pdf_document
date: "2023-06-06"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(pdftools)
library(tesseract)
library(stringr)
library(rlist)
library(dplyr)
library(tidyverse)
```

```{r}
# extracting data
data <- pdf_data("./data/armor-da-pam-600-3-a-2.pdf")

# establishing MOS
MOS <- "Armor"

# we want pages 3-9

pages3to9 <- list.rbind(data[3:9])
pages3to9sep <- as.character(pages3to9$text)
fulltext <- paste(pages3to9sep, collapse = " ")
fulltext
```

```{r}
# find all of our KD paragraphs
KDs <- unlist(str_extract_all(fulltext, "(Key)(\\h)(developmental).*?(?=(\\h[a-z]\\.\\h)|(Examples))|(KD).*?(?=\\h[a-z]\\.\\h)"))

#get rid of a broadening that made its way in

KDs <- KDs[-4]
KDs
```

```{r}
# make a dataframe to start storing

# variable name
columns <- c("MOS", "Rank", "Assignment", "Type")

# data frame
dataframe <- data.frame(matrix(nrow = 100, ncol = length(columns)))

# assigning column names
colnames(dataframe) <- columns

```


```{r}
# clean the KDs

# LT and CAP hard, might as well just hard code those in

dataframe$MOS <- MOS
dataframe[1,c(2,3,4)] <- c("LT", "Platoon Leader", "KD")
dataframe[2,c(2,3,4)] <- c("CAP", "Company/Troop Commander", "KD")
dataframe[3,c(2,3,4)] <- c("CAP", "Staff Officer", "KD")

# now that we've dealt with those...
KDs
KDsClean <- KDs[3:5]
KDassignments <- unlist(str_extract_all(KDsClean, "\\(\\d\\).*?(?=(\\(\\d\\))|(Note)|(There))"))
KDassignmentsclean1 <- unlist(str_extract_all(KDassignments, "(?<=\\(\\d\\)\\h).*(?=\\h\\(SA)"))
KDassignmentsclean <- unlist(str_extract_all(KDassignments, "(?<=\\(\\d\\)\\h).*(?=\\h$)"))
KDassignmentsclean[3] <- KDassignmentsclean1[1]
```

```{r}
#adding to dataframe

dataframe$Assignment[4:14] <- KDassignmentsclean
dataframe$Rank[4:8] <- "MAJ"
dataframe$Rank[9:11] <- "LTC"
dataframe$Rank[12:14] <- "COL"
dataframe$Type[4:14] <- "KD"
```

```{r}
# get broadening assignments
broadeningparagraphs <- unlist(str_extract_all(fulltext, "[Bb]roadening\\h[Aa]ssignments.*?(?=Skills\\h(and)\\h(Attributes))"))

# clean

broadeningparagraphs <- broadeningparagraphs[-1]
broadeningparagraphs[2] <- str_extract(broadeningparagraphs[2], "c\\.\\h(Broadening).*$")
broadeningparagraphs
broadeningparagraphs <- unlist(broadeningparagraphs)

# note that the captain ones are not exactly the same as normal broadening because they have to be completed after KD is fulfilled

# breaking down by numbers + letters
broadeningassignments <- unlist(str_extract_all(broadeningparagraphs, "(?<=\\h\\(.{1,2}\\)\\h).*?(?=(\\h\\(.{1,2}\\)\\h)|$)"))

# cleaning
broadeningassignmentsclean1 <- str_remove_all(broadeningassignments, "(\\h(c)\\.\\h)|(\\h(d)\\.\\h)|(\\(.*\\))")
broadeningassignmentsclean2 <- str_remove_all(broadeningassignmentsclean1, "(\\*.*$)|(6\\h.*$)")
broadeningassignmentsclean <- str_remove_all(broadeningassignmentsclean2, "\\h$")
broadeningassignmentsclean
```

```{r}
# adding to data frame
dataframe$Assignment[15:61] <- broadeningassignmentsclean
dataframe$Type[15:61] <- "DEV"
dataframe$Rank[15:28] <- "CAP"
dataframe$Rank[29:42] <- "MAJ"
dataframe$Rank[43:51] <- "LTC"
dataframe$Rank[52:61] <- "COL"

#final data

fulldata <- dataframe[1:61,]

write.csv(fulldata, "./data/14_06_2023_ArmorR.csv")
```

