---
title: " "
weight: 4
draft: false
output: html_document
---

```{css, echo=FALSE}
/* this chunnk of code centers all of the headings */
h1, h2, h3 {
  text-align: center;
}
```

### Data

Data was collected and joined on tract GEOID across the following sources:

-	2013-2017 [American Community Survey](https://www.census.gov/acs/www/data/data-tables-and-tools/data-profiles/2017/): highest educational attainment, unemployment.
-	Missouri Census Data Center’s 2018 [Geocorr database](http://mcdc.missouri.edu/applications/geocorr.html) to understand tracts in terms of their corresponding census places, namely cities.
-	[Eviction Lab at Princeton University](https://evictionlab.org/): Census tract-level data on eviction rates, poverty rate, median income, and race.
-	[Policy Atlas](https://lawatlas.org/topics): State level laws on eviction, fair housing, and landlord-tenant laws.
-	The sample consist of census tracts in cities with a population between 100,000-300,000.
-	The final dataset contained 2,600 census tracts in 78 cities across the U.S.

### Methods

* A regression model was estimated from data at the census tract-level, which included socio-demographic variables, city-level fixed effects, and state-level housing variables. The variables in our models were chosen based on a thorough literature search. We did further analysis to determine factors that were not significant or were highly correlated with other variables. These variables, in addition to variables with high variance inflation factors or other variables with high collinearity by correlation matrix, were dropped.

* A visualization of the Eviction Intensity Index created using standardized residuals from the regression model. While the goal of most statistical analyses is to focus on what the model ‘explains,’ that is, its predictions, and to determine how changes in the explanatory factors might impact these predictions, here we are taking the opposite approach. After we have done the best job possible of constructing a statistical model to explain eviction rates, we focus on what remains unexplained. In this way, we attempt to explore and focus on the model’s large, positive “misses” as a way to identify census track locations that are, in essence, eviction hotspots, for whatever the reason. Furthermore, if eviction hotspots are clustered in a handful of cities as opposed to being more-or-less randomly distributed across the various cities included in the analysis, then we have further evidence of potential systemic, local, and structural issues that may be resulting in unexpectedly high eviction rates.

* A visualization of the key sociodemographic variables identified in the regression model to be correlated with eviction and their evolution between 2013-2018.

