---
title: "SentimentAnalysis"
author: "Xinyi Zhu"
date: "6/26/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# install.packages("sentimentr")
library(sentimentr)
library(tidyverse)
library(ggplot2)
```

```{r}
packages <- c("rvest", "dplyr", "purrr", "readr", 
              "stringr", "magrittr", "httr", "stringr", "ggplot2",
              "ggmap", "mapview")
for (pkgs in packages){
  if(!require(pkgs, character.only = TRUE)){
    install.packages(pkgs)
    library(pkgs)
  }
}

```

```{r}
df <- read.csv("/Users/jessie/Desktop/ISU/2020Summer/DSPG/Project/Hotline/Dataset/rough_data_trans-2.csv", stringsAsFactors = FALSE)
df$Call_Transcript[1]
```

```{r}
Text <- strsplit(df$Call_Transcript[1], "\n") #/n splitting the text... can change if you rather work with "1" and "2" rather than "speaker 1" and "speaker 2"
people_on_phone <- c("speaker 1", "speaker 2")
TidyspeechText <- lapply(Text, function(thisText){
  strsplit(thisText, ":") %>% # (1.)
    lapply(function(x){
      if(x[1] %in% people_on_phone){ # (2.)
        check <- data.frame(currently_speaking = x[1], text = paste(x[-1], collapse = ":"))
      } else{
        check <- data.frame(currently_speaking = NA, text = paste(x, collapse = ":")) # (3.)
      }
      
      return(check)
      
    }) %>%
    bind_rows %>%
    mutate(call_record = cumsum(!is.na(currently_speaking))) %>%
    group_by(call_record) %>%
    summarise(currently_speaking = currently_speaking[1], split_transcript = paste(text, collapse = "\n"))
})
TidyspeechText
```

```{r}
# TidyspeechText is a list, list does not work in the sentiment_by() function
tidydf <- as.data.frame(TidyspeechText)
tidydf
```

```{r}
# get sentiment scores
sentiment_by(get_sentences(tidydf$split_transcript)) 
sentiment_analysis_conversation1<- sentiment_by(get_sentences(tidydf$split_transcript))
```


```{r}
# Merge 2 data frames
sentiment_analysis_conversation1 <- sentiment_analysis_conversation1 %>% 
  rename(call_record = element_id)
conversation_1merge<-merge(tidydf, sentiment_analysis_conversation1, by ="call_record")
view(conversation_1merge)

ggplot(conversation_1merge, 
                  aes(x=call_record, y=ave_sentiment, color = currently_speaking)) + geom_line()

```

```{r}
# define negative/ positive words
extract_sentiment_terms(tidydf$split_transcript)
```

