---
title: "Crop Data Layer S. Wasco"
author: "Owen Hart"
date: "7/28/2020"
output: html_document
---

```{r}
library(R.utils)
library(data.table)
library(tidyr)
library(dplyr)
library(readr)
library(ggplot2)
library(sf)
library(leaflet)
library(reshape2)
library(raster)
library(tigris)
library(viridis)
```

```{r}
south_wasco_points <- st_read("../data/shps/swsd")
```


Aaron's script
```{r}
# FUNCTION TO CREATE A SEPARATE RASTER FOR EACH SPATIAL OBJECT (e.g. Census Tract)
crop_mask_raster_to_spatial <- function(raster_obj, sf_obj) {
  library(raster)
  library(sf)
  library(data.table)
  for (i in 1:nrow(sf_obj)) {
    sf_row <- sf_obj[i,]
    sp_row <- as(st_geometry(sf_row), 'Spatial')
    sp_row <- spTransform(sp_row, crs(raster_obj))
    crp <- crop(raster_obj, sp_row)
    msk <- mask(crp, sp_row)
   
    if (exists("out_ls") == F) out_ls <- list()
    out_ls[sf_row$GEOID] <- msk
  }
  out_ls
}
 
# FUNCTION TO GET ACRES PER LAND COVER ITEM PER SPATIAL OBJECT
raster_sqm_to_acres <- function(raster_list) {
  options(scipen = 999)
  for (i in 1:length(raster_list)) {
    sqm <- data.table::setDT(aggregate(getValues(area(raster_list[[i]], weights=FALSE)), by=list(getValues(raster_list[[i]])), sum))
    sqa <- sqm[,.(class = Group.1, sqm = x, acres = x*0.00024711)]
    sqa$geoid <- names(raster_list[i])
    if (exists("out_dt")) out_dt <- data.table::rbindlist(list(out_dt, sqa))
    else out_dt <- sqa
  }
  out_dt
}
 
# READ RASTER FILE
raster_2017 <- raster::raster("~/git/dspg20wasco/data/raster/CDL_2017_41065.tif")
raster_2016 <- raster::raster("~/git/dspg20wasco/data/raster/CDL_2016_41065.tif")
raster_2015 <- raster::raster("~/git/dspg20wasco/data/raster/CDL_2015_41065.tif")
# GET SPATIAL GEORGAPHIES (sf file)
#sf <- sf::st_as_sf(tigris::tracts("OR", "Wasco County"))
sf <- sf::st_as_sf(tigris::block_groups("OR", "Wasco County"))
# CREATE A SEPARATE RASTER FOR EACH SPATIAL OBJECT
list_of_geo_rasters_17 <- crop_mask_raster_to_spatial(raster_2017, sf)
list_of_geo_rasters_16 <- crop_mask_raster_to_spatial(raster_2016, sf)
list_of_geo_rasters_15 <- crop_mask_raster_to_spatial(raster_2015, sf)

# GET ACRES PER LAND COVER ITEM PER SPATIAL OBJECT
crop_acres_per_geo_17 <- raster_sqm_to_acres(list_of_geo_rasters_17)
crop_acres_per_geo_16 <- raster_sqm_to_acres(list_of_geo_rasters_16)
crop_acres_per_geo_15 <- raster_sqm_to_acres(list_of_geo_rasters_15)

# ADD YEAR
yr17 <- stringr::str_match("~/git/dspg20wasco/data/raster/CDL_2017_41065.tif", "_(\\d\\d\\d\\d)")[,2]
yr16 <- stringr::str_match("~/git/dspg20wasco/data/raster/CDL_2016_41065.tif", "_(\\d\\d\\d\\d)")[,2]
yr15 <- stringr::str_match("~/git/dspg20wasco/data/raster/CDL_2015_41065.tif", "_(\\d\\d\\d\\d)")[,2]
crop_acres_per_geo_17$year <- yr17
crop_acres_per_geo_16$year <- yr16
crop_acres_per_geo_15$year <- yr15
# CONVERT CODES TO LAND COVER/CROP NAMES
crop_acres_per_geo_17$desc <- cdlTools::updateNamesCDL(crop_acres_per_geo_17$class)
crop_acres_per_geo_16$desc <- cdlTools::updateNamesCDL(crop_acres_per_geo_16$class)
crop_acres_per_geo_15$desc <- cdlTools::updateNamesCDL(crop_acres_per_geo_15$class)

# MERGE SPATIAL GEOGRAPHIES WITH THE CROP ACREAGE DATA
acres_17 <- merge(sf, crop_acres_per_geo_17, by.x = "GEOID", by.y = "geoid")
acres_16 <- merge(sf, crop_acres_per_geo_16, by.x = "GEOID", by.y = "geoid")
acres_15 <- merge(sf, crop_acres_per_geo_15, by.x = "GEOID", by.y = "geoid")
# ASSIGN A CRS
acres_17 <- sf::st_set_crs(acres_17, 4269)
acres_16 <- sf::st_set_crs(acres_16, 4269)
acres_15 <- sf::st_set_crs(acres_15, 4269)

```

saving data
```{r}
saveRDS(acres_17, "../data/app_acres_17.Rds")
saveRDS(acres_16, "../data/app_acres_16.Rds")
saveRDS(acres_15, "../data/app_acres_15.Rds")
```

```{r}
acres_17
```


Winter Wheat
```{r}
colors_ww <- colorQuantile(viridis_pal(option = "D")(3), 
                             domain = rbind(acres_17[acres_17$desc == "Winter Wheat", ],
                                            acres_16[acres_16$desc == "Winter Wheat", ],
                                            acres_15[acres_15$desc == "Winter Wheat", ])$acres)

cdl_ww <- leaflet() %>%
  addProviderTiles(providers$CartoDB.Positron) %>%
  addPolylines(
    data = south_wasco_points,
    color = "red",
    weight = 2,
    opacity = .7,
    group = "Basemap",
    label = "South Wasco Region") %>%
  addPolygons(data = acres_17[acres_17$desc == "Winter Wheat", ],
              weight = .3,
              opacity = 1,
              fillOpacity = .7,
              group = "2017",
              fillColor = ~ colors_ww(acres),
              label = ~lapply(paste(sep = "", "Census Tract: ", 
                                    acres_17[acres_17$desc == "Winter Wheat", ]$TRACTCE, "<br/>",
                                    "<strong> Number of Acres: <strong>",
                                    round(acres_17[acres_17$desc == "Winter Wheat", ]$acres), 0),
                              htmltools::HTML)) %>%
  addLegend(
    data = rbind(acres_17[acres_17$desc == "Winter Wheat", ],
                 acres_16[acres_16$desc == "Winter Wheat", ],
                 acres_15[acres_15$desc == "Winter Wheat", ]),
    "bottomright",
    pal = colors_ww,
    values = ~ acres,
    labFormat = function(type, cuts, p) {
      n = length(cuts)
      p = paste0(round(p * 100), '%')
      cuts = paste0(formatC(cuts[-n]), " - ", formatC(cuts[-1]))},
    title = "Number of Acres of Winter Wheat<br>by Block Group",
    opacity = .7,
    na.label = "NA") %>%
  addPolygons(data = acres_16[acres_16$desc == "Winter Wheat", ],
              weight = .3,
              opacity = 1,
              fillOpacity = .7,
              group = "2016",
              fillColor = ~ colors_ww(acres),
              label = ~lapply(paste(sep = "", "Census Tract: ", 
                                    acres_16[acres_16$desc == "Winter Wheat", ]$TRACTCE, "<br/>",
                                    "<strong> Number of Acres: <strong>",
                                    round(acres_16[acres_16$desc == "Winter Wheat", ]$acres), 0),
                              htmltools::HTML)) %>% 
  addPolygons(data = acres_15[acres_15$desc == "Winter Wheat", ],
              weight = .3,
              opacity = 1,
              fillOpacity = .7,
              group = "2015",
              fillColor = ~ colors_ww(acres),
              label = ~lapply(paste(sep = "", "Census Tract: ", 
                                    acres_15[acres_15$desc == "Winter Wheat", ]$TRACTCE, "<br/>",
                                    "<strong> Number of Acres: <strong>",
                                    round(acres_15[acres_15$desc == "Winter Wheat", ]$acres), 0),
                              htmltools::HTML)) %>% 
  addLayersControl(
    baseGroups = c("2017", "2016", "2015"),
    options = layersControlOptions(collapsed = FALSE))
```


```{r}
colors_bar <- colorQuantile(viridis_pal(option = "D")(3), 
                             domain = rbind(acres_17[acres_17$desc == "Barley", ],
                                            acres_16[acres_16$desc == "Barley", ],
                                            acres_15[acres_15$desc == "Barley", ])$acres)
cdl_barley <- leaflet() %>%
  addProviderTiles(providers$CartoDB.Positron) %>%
  addPolylines(
    data = south_wasco_points,
    color = "red",
    weight = 2,
    opacity = .7,
    group = "Basemap",
    label = "South Wasco Region") %>%
  addPolygons(data = acres_17[acres_17$desc == "Barley", ],
              weight = .3,
              opacity = 1,
              fillOpacity = .7,
              group = "2017",
              fillColor = ~ colors_bar(acres),
              label = ~lapply(paste(sep = "", "Census Tract: ", 
                                    acres_17[acres_17$desc == "Barley", ]$TRACTCE, "<br/>",
                                    "<strong> Number of Acres: <strong>",
                                    round(acres_17[acres_17$desc == "Barley", ]$acres), 0),
                              htmltools::HTML)) %>%
  addLegend(
    data = rbind(acres_17[acres_17$desc == "Barley", ],
                          acres_16[acres_16$desc == "Barley", ],
                          acres_15[acres_15$desc == "Barley", ]),
    "bottomright",
    pal = colors_bar,
    values = ~ acres,
    labFormat = function(type, cuts, p) {
      n = length(cuts)
      p = paste0(round(p * 100), '%')
      cuts = paste0(formatC(cuts[-n]), " - ", formatC(cuts[-1]))},
    title = "Number of Acres of Barley<br>by Block Group",
    opacity = .7,
    na.label = "NA") %>%
  addPolygons(data = acres_16[acres_16$desc == "Barley", ],
              weight = .3,
              opacity = 1,
              fillOpacity = .7,
              group = "2016",
              fillColor = ~ colors_bar(acres),
              label = ~lapply(paste(sep = "", "Census Tract: ", 
                                    acres_16[acres_16$desc == "Barley", ]$TRACTCE, "<br/>",
                                    "<strong> Number of Acres: <strong>",
                                    round(acres_16[acres_16$desc == "Barley", ]$acres), 0),
                              htmltools::HTML)) %>%
  addPolygons(data = acres_15[acres_15$desc == "Barley", ],
              weight = .3,
              opacity = 1,
              fillOpacity = .7,
              group = "2015",
              fillColor = ~ colors_bar(acres),
              label = ~lapply(paste(sep = "", "Census Tract: ", 
                                    acres_15[acres_15$desc == "Barley", ]$TRACTCE, "<br/>",
                                    "<strong> Number of Acres: <strong>",
                                    round(acres_15[acres_15$desc == "Barley", ]$acres), 0),
                              htmltools::HTML)) %>%
  addLayersControl(
    baseGroups = c("2017", "2016", "2015"),
    options = layersControlOptions(collapsed = FALSE))
```


```{r}
colors_alf <- colorQuantile(viridis_pal(option = "D")(3), 
                             domain = rbind(acres_17[acres_17$desc == "Alfalfa", ],
                                            acres_16[acres_16$desc == "Alfalfa", ],
                                            acres_15[acres_15$desc == "Alfalfa", ])$acres)
cdl_alfalfa <- leaflet() %>%
  addProviderTiles(providers$CartoDB.Positron) %>%
  addPolylines(
    data = south_wasco_points,
    color = "red",
    weight = 2,
    opacity = .7,
    group = "Basemap",
    label = "South Wasco Region") %>%
  addPolygons(data = acres_17[acres_17$desc == "Alfalfa", ],
              weight = .3,
              opacity = 1,
              fillOpacity = .7,
              group = "2017",
              fillColor = ~ colors_alf(acres),
              label = ~lapply(paste(sep = "", "Census Tract: ", 
                                    acres_17[acres_17$desc == "Alfalfa", ]$TRACTCE, "<br/>",
                                    "<strong> Number of Acres: <strong>",
                                    round(acres_17[acres_17$desc == "Alfalfa", ]$acres), 0),
                              htmltools::HTML)) %>%
  addLegend(
    data = rbind(acres_17[acres_17$desc == "Alfalfa", ],
                 acres_16[acres_16$desc == "Alfalfa", ],
                 acres_15[acres_15$desc == "Alfalfa", ]),
    "bottomright",
    pal = colors_alf,
    values = ~ acres,
    labFormat = function(type, cuts, p) {
      n = length(cuts)
      p = paste0(round(p * 100), '%')
      cuts = paste0(formatC(cuts[-n]), " - ", formatC(cuts[-1]))},
    title = "Number of Acres of Alfalfa<br>by Block Group",
    opacity = .7,
    na.label = "NA") %>%
  addPolygons(data = acres_16[acres_16$desc == "Alfalfa", ],
              weight = .3,
              opacity = 1,
              fillOpacity = .7,
              group = "2016",
              fillColor = ~ colors_alf(acres),
              label = ~lapply(paste(sep = "", "Census Tract: ", 
                                    acres_16[acres_16$desc == "Alfalfa", ]$TRACTCE, "<br/>",
                                    "<strong> Number of Acres: <strong>",
                                    round(acres_16[acres_16$desc == "Alfalfa", ]$acres), 0),
                              htmltools::HTML)) %>%
  addPolygons(data = acres_15[acres_15$desc == "Alfalfa", ],
              weight = .3,
              opacity = 1,
              fillOpacity = .7,
              group = "2015",
              fillColor = ~ colors_alf(acres),
              label = ~lapply(paste(sep = "", "Census Tract: ", 
                                    acres_15[acres_15$desc == "Alfalfa", ]$TRACTCE, "<br/>",
                                    "<strong> Number of Acres: <strong>",
                                    round(acres_15[acres_15$desc == "Alfalfa", ]$acres), 0),
                              htmltools::HTML)) %>%
  addLayersControl(
    baseGroups = c("2017", "2016", "2015"),
    options = layersControlOptions(collapsed = FALSE))
```


```{r}
colors_cher <- colorQuantile(viridis_pal(option = "D")(3), 
                             domain = rbind(acres_17[acres_17$desc == "Cherries", ],
                                            acres_16[acres_16$desc == "Cherries", ],
                                            acres_15[acres_15$desc == "Cherries", ])$acres)
cdl_cherries <- leaflet() %>%
  addProviderTiles(providers$CartoDB.Positron) %>%
  addPolylines(
    data = south_wasco_points,
    color = "red",
    weight = 2,
    opacity = .7,
    group = "Basemap",
    label = "South Wasco Region") %>%
  addPolygons(data = acres_17[acres_17$desc == "Cherries", ],
              weight = .3,
              opacity = 1,
              fillOpacity = .7,
              group = "2017",
              fillColor = ~ colors_cher(acres),
              label = ~lapply(paste(sep = "", "Census Tract: ", 
                                    acres_17[acres_17$desc == "Cherries", ]$TRACTCE, "<br/>",
                                    "<strong> Number of Acres: <strong>",
                                    round(acres_17[acres_17$desc == "Cherries", ]$acres), 0),
                              htmltools::HTML)) %>%
  addLegend(
    data = rbind(acres_17[acres_17$desc == "Cherries", ], 
                 acres_16[acres_16$desc == "Cherries", ],
                 acres_15[acres_15$desc == "Cherries", ]),
    "bottomright",
    pal = colors_cher,
    values = ~acres,
    labFormat = function(type, cuts, p) {
      n = length(cuts)
      p = paste0(round(p * 100), '%')
      cuts = paste0(formatC(cuts[-n]), " - ", formatC(cuts[-1]))},
    title = "Number of Acres of Cherries<br>by Block Group",
    opacity = .7,
    na.label = "NA") %>%
  addPolygons(data = acres_16[acres_16$desc == "Cherries", ],
              weight = .3,
              opacity = 1,
              fillOpacity = .7,
              group = "2016",
              fillColor = ~ colors_cher(acres),
              label = ~lapply(paste(sep = "", "Census Tract: ", 
                                    acres_16[acres_16$desc == "Cherries", ]$TRACTCE, "<br/>",
                                    "<strong> Number of Acres: <strong>",
                                    round(acres_16[acres_16$desc == "Cherries", ]$acres), 0),
                              htmltools::HTML)) %>%
  addPolygons(data = acres_15[acres_15$desc == "Cherries", ],
              weight = .3,
              opacity = 1,
              fillOpacity = .7,
              group = "2015",
              fillColor = ~ colors_cher(acres),
              label = ~lapply(paste(sep = "", "Census Tract: ", 
                                    acres_15[acres_15$desc == "Cherries", ]$TRACTCE, "<br/>",
                                    "<strong> Number of Acres: <strong>",
                                    round(acres_15[acres_15$desc == "Cherries", ]$acres), 0),
                              htmltools::HTML)) %>%
  addLayersControl(
    baseGroups = c("2017", "2016", "2015"),
    options = layersControlOptions(collapsed = FALSE))
```


```{r}
cdl_ww
cdl_barley
cdl_alfalfa
cdl_cherries
```

