---
title: "Sage Brief Analysis"
author: "Sarah McDonald"
date: "7/28/2020"
#output: html_document
output: md_document
always_allow_html: true
---

```{r, warning = F, message = F }
library(dplyr)
library(ggplot2)
library(readxl)
library(tidyr)
library(ggrepel)
  
data <- read.csv("/sfs/qumulo/qhome/sm9dv/dspg20STW/src/sage_brief/stw_edu_region.csv")


data$less_than_bach <- rowSums(data[, c("minedu_0", "minedu_12", "minedu_14")])


soc_region <- data %>% 
  select(state.region, X2010.SOC.Code, less_than_bach, N) %>% 
  group_by(state.region, X2010.SOC.Code)%>%
  summarise(less_than_bach = sum(less_than_bach), 
            N = sum(N), 
            per = less_than_bach/N)

xwalk <- read_xls("/sfs/qumulo/qhome/sm9dv/dspg20STW/data/ncses_stw/original/onet/2010_to_SOC_Crosswalk.xls", skip = 3)

soc_region_chart <- merge(soc_region, xwalk[, c("2010 SOC Code", "2010 SOC Title")], by.x = "X2010.SOC.Code", by.y = "2010 SOC Code", all.x = T)
```


First, we will identify the SOC codes in which 100% of the jobs did not require a bachelor's degree:
```{r}
# socs where 100% of the jobs did not require a bachelors degree or above
soc_100 <- soc_region %>% filter(per == 1)

# northeast
unique(pull(soc_100[soc_100$state.region == "Northeast", "X2010.SOC.Code"]))
unique(substr(unique(pull(soc_100[soc_100$state.region == "Northeast", "X2010.SOC.Code"])), 1, 2))

# midwest
unique(pull(soc_100[soc_100$state.region == "Midwest", "X2010.SOC.Code"]))
unique(substr(unique(pull(soc_100[soc_100$state.region == "Midwest", "X2010.SOC.Code"])), 1, 2 ))

# south
unique(pull(soc_100[soc_100$state.region == "South", "X2010.SOC.Code"]))
unique(substr(unique(pull(soc_100[soc_100$state.region == "South", "X2010.SOC.Code"])), 1, 2 ))

# west
unique(pull(soc_100[soc_100$state.region == "West", "X2010.SOC.Code"]))
unique(substr(unique(pull(soc_100[soc_100$state.region == "West", "X2010.SOC.Code"])),1,2))

# see how many socs whre 100 % of jobs did not require a bacheors degree or above by region
soc_100 %>% select(state.region, X2010.SOC.Code) %>%group_by(state.region) %>% summarize(countSOCs = n()) 


# major occ groups 47 and 49 have the most of these jobs
  soc_100 %>% ungroup() %>%select( X2010.SOC.Code, state.region) %>%
    mutate(maj_occ = substr(X2010.SOC.Code, start = 1, stop = 2)) %>% 
    group_by(state.region, maj_occ) %>%
    summarize(countMajOcc = n()) %>%
    spread(key = maj_occ, value = countMajOcc)
  

```

Boxplots

```{r}
  is_outlier <- function(x) {
    return(x < quantile(x, 0.25) - 1.5 * IQR(x) | x > quantile(x, 0.75) + 1.5 * IQR(x))
  }

  soc_region <- soc_region %>%
    group_by(state.region) %>%
    mutate(q1 = quantile(per, 0.25) - 1.5 * IQR(per)) %>%
    ungroup() 
  
  soc_region<-soc_region %>% mutate(outlier = ifelse(soc_region$per < q1, X2010.SOC.Code, NA))
  
  ggplot(soc_region, aes(x = per, y = state.region) )  + geom_boxplot()+
    geom_text_repel(aes(label = outlier), na.rm = TRUE) + 
    labs(title = "Share of STW Job Ads Requiring less than a\n Bachelor's Degree by Region and SOC", x= "", y = "")
  
```


```{r}
  data$less_than_bach_per <- data$less_than_bach/data$N
# onet level
 onet <- data %>% 
    group_by(state.region) %>%
    mutate(q1 = quantile(less_than_bach_per, 0.25) - 1.5 * IQR(less_than_bach_per)) %>%
    ungroup() 
  
 onet<-onet %>% mutate(outlier = ifelse(less_than_bach_per < q1, onet, NA))
 
 ggplot(onet, aes(x = less_than_bach_per, y = state.region) )  + geom_boxplot()+
   geom_text_repel(aes(label = outlier), na.rm = TRUE) +
  labs(title = "Share of STW Job Ads Requiring less than a\n Bachelor's Degree by Region and ONET", x= "", y = "")

```









