---
title: "housing_analysis"
output: html_document
date: "2023-07-28"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#Import libraries
library(ggplot2)
library(wordcloud)
library(RColorBrewer)
library(wordcloud2)
library(reshape)
library(tm)
library(stringr)
library(plotly)
library(dplyr)
```

```{r}
cbPalette <- c("#999999", "#E69F00", "#56B4E9", "#009E73", "#F0E442", "#0072B2", "#D55E00", "#CC79A7")
```


```{r}
#Reads in housing data
housing_data <- read.csv('/Users/marijkevandergeer/Documents/GitHub/dspg23census/project_website/Finding_Housing/Housing_data.csv')
```

```{r}
#Creates a bar graph of sub-category types
sub_cat_counts <- function(state) {
  if(state=="All Sample States") {
    sub_cats <- ggplot(data=subset(housing_data, !is.na(Sub.categories)), aes(x=Sub.categories)) + geom_bar(fill="blue") + labs(x="Sub-Category", y="Counts", title="Types of Sub-Categories") + theme(axis.text.x = element_text(angle = 25))
    ggplotly(sub_cats)
  }
  else { #fix
    State <- str_to_title(state)
    state_input <- housing_data[housing_data[, "State"]==state, ]
    state_df <- data.frame()
    state_df <- rbind(state_df, state_input)
    sub_cats <- ggplot(state_df, aes(x=Sub.categories)) + geom_bar(fill="blue") + labs(x="Sub-Category", y="Counts", title="Types of Sub-Categories") + theme(axis.text.x = element_text(angle = 25))
    ggplotly(sub_cats)
  }
}

sub_cat_counts("All Sample States")
```


```{r}
#Tool
#Number/types of tools-pie chart

#fix
tool_barchart <- function(state) {
  if(state=="All Sample States") {
    tools <- ggplot(housing_data, aes(x=Tool)) + geom_bar(fill="blue") + labs(x="Tool", y="Count", title="Types of Tools") + theme(axis.text.x = element_text(angle = 45))
  ggplotly(tools)
  }
  else {
    State <- str_to_title(state)
    state_input <- housing_data[housing_data[, "State..Country"]==state, ]
    state_df <- data.frame()
    state_df <- rbind(state_df, state_input)
    tools <- ggplot(state_df, aes(x=Tool)) + geom_bar(fill="blue") + labs(x="Tool", y="Count", title="Types of Tools") + theme(axis.text.x = element_text(angle = 45))
  ggplotly(tools)
  }
}

tool_barchart("California")
```


```{r}
#Word cloud for tool names
#Input is designated state
tool_cloud <- function(state) {
  if(state=="all states"){
    combo <- ""
    for (i in 1:nrow(housing_data)) {
      combo <- paste(combo, housing_data$Tool.Name[i], sep="")
    }
  }
  else{
  #Combines all variables into one string
    combo <- ""
    for (i in 1:nrow(housing_data)) {
      if(housing_data$State[i]==state) {
        combo <- paste(combo, housing_data$Tool.Name[i], sep="")
      }
    }
  }

  #Turns string into corpus of words
  docs <- Corpus(VectorSource(combo))

  #Cleaning of corpus
  docs <- docs %>% tm_map(removeNumbers) %>% tm_map(removePunctuation) %>% tm_map(stripWhitespace)
  docs <- tm_map(docs, content_transformer(tolower))
  docs <- tm_map(docs, removeWords, stopwords("english"))

  #Turns corpus into term-document-matrix
  dtm <- TermDocumentMatrix(docs)
  mtx <- as.matrix(dtm)
  words <- sort(rowSums(mtx), decreasing = TRUE)
  df <- data.frame(word = names(words), freq=words)

  #Creates wordcloud
  set.seed(33)

  cloud <- wordcloud(words = df$word, freq = df$freq, min.freq = 1, max.words = 100, random.order = FALSE, rot.per = 0, colors = brewer.pal(4, "Set1"))
  
  return(cloud)
}
```


```{r}
#Word cloud for variable names
#Input is designated state
variable_cloud <- function(state) {
  if(state=="all states"){
    combo <- ""
    for (i in 1:nrow(housing_data)) {
      combo <- paste(combo, housing_data$Variables[i], sep="")
    }
  }
  else{
  #Combines all variables into one string
    combo <- ""
    for (i in 1:nrow(housing)) {
      if(housing_data$State[i]==state) {
        combo <- paste(combo, housing_data$Variables[i], sep="")
      }
    }
  }

  #Turns string into corpus of words
  docs <- Corpus(VectorSource(combo))

  #Cleaning of corpus
  docs <- docs %>% tm_map(removeNumbers) %>% tm_map(removePunctuation) %>% tm_map(stripWhitespace)
  docs <- tm_map(docs, content_transformer(tolower))
  docs <- tm_map(docs, removeWords, stopwords("english"))

  #Turns corpus into term-document-matrix
  dtm <- TermDocumentMatrix(docs)
  mtx <- as.matrix(dtm)
  words <- sort(rowSums(mtx), decreasing = TRUE)
  df <- data.frame(word = names(words), freq=words)

  #Creates wordcloud
  set.seed(33)

  cloud <- wordcloud(words = df$word, freq = df$freq, min.freq = 1, max.words = 100, random.order = FALSE, rot.per = 0, colors = brewer.pal(4, "Set1"))
  
  return(cloud)
}
```

```{r}
#Data Sources-Census
#Number/types of census sources-bar chart, pie chart, count

#fix: exclude if value is NA
#fix: by state
census <- ggplot(housing, aes(x=Data.Sources.Census)) + geom_bar(fill="blue") + labs(x="Census Source", y="Count", title="Types of Census Sources") + theme(axis.text.x = element_text(angle = 45))
ggplotly(census)
```

```{r}
#Data Sources-Non Census
#Number/types of non-census sources-bar chart, pie chart, count

#fix: exclude if value is NA
#fix: by state
non_census <- ggplot(housing, aes(x=Data.Sources.Non.Census)) + geom_bar(fill="blue") + labs(x="Data Sources", y="Count", title="Data Sources") + theme(axis.text.x = element_text(angle = 45))
ggplotly(non_census)
```

```{r}
hous_pie_graph_noncensus <- function(selected_state, data_table) {
  if (selected_state == "All Sample States") {
    data_to_use = data_table
  } else {
    data_to_use = data_table[data_table$State == selected_state, ]
  }
  
  countinue <- data_to_use %>% group_by(Data.Sources.Non.Census) %>% summarize(count = n())
  colnames(countinue) <- c("data source", "count")
  countinue <- countinue[countinue$`data source` != "", ]

  # Adding a title to the pie graph
  title <- paste("Housing Data Source (Non Census) \n Distribution in", selected_state)
  
  par(mfrow = c(1, 1), mar = c(4, 4, 2, 2))
  pie(countinue$count, labels = countinue$`data source`, border = "white", col = cbPalette, cex = 1, main = title)
}
hous_pie_graph_noncensus("All Sample States", housing)
```

```{r}
hous_sub_cat_and_tool <- function(selected_state){
  df_stack2 <- data.frame(
    Tools = character(),
    sub = character(),
    count = numeric())
  
  col_name = c("Tools","sub","count")
  colnames(df_stack2) <- col_name
  
  if (selected_state == "All Sample States and Territories" ){
    data_to_use = housing_data
  }
  else{
    data_to_use = housing_data[housing_data$State..Country== selected_state,]
  }
  
  for (i in 1:nrow(data_to_use)) {
    #---residential mobility---
    if (any(grepl("Residential Mobility", data_to_use[i,3]))) {
      if(any(grepl("Table", data_to_use[i,4]))){
        new_row <- c("Table", "Residential Mobility",54)
        df_stack2 <- rbind(df_stack2, new_row)
      }
      if(any(grepl("Table Download", data_to_use[i,4]))){
        new_row <- c("Table Download", "Residential Mobility",54)
        df_stack2 <- rbind(df_stack2, new_row)
      }
      if(any(grepl("Report", data_to_use[i,4]))){
        new_row <- c("Report", "Residential Mobility",54)
        df_stack2 <- rbind(df_stack2, new_row)
      }
      if(any(grepl("Map", data_to_use[i,4]))){
        new_row <- c("Map", "Residential Mobility",54)
        df_stack2 <- rbind(df_stack2, new_row)
      }
      if(any(grepl("Data Visualization", data_to_use[i,4]))){
        new_row <- c("Data Visualization", "Residential Mobility",54)
        df_stack2 <- rbind(df_stack2, new_row)
      }
      if(any(grepl("Infographic", data_to_use[i,4]))){
        new_row <- c("Infographic", "Residential Mobility",54)
        df_stack2 <- rbind(df_stack2, new_row)
      }
    }
    #---projections---
    if (any(grepl("Projections", data_to_use[i,3]))) {
      if(any(grepl("Table", data_to_use[i,4]))){
        new_row <- c("Table", "Projections",54)
        df_stack2 <- rbind(df_stack2, new_row)
      }
      if(any(grepl("Table Download", data_to_use[i,4]))){
        new_row <- c("Table Download", "Projections",54)
        df_stack2 <- rbind(df_stack2, new_row)
      }
      if(any(grepl("Report", data_to_use[i,4]))){
        new_row <- c("Report", "Projections",54)
        df_stack2 <- rbind(df_stack2, new_row)
      }
      if(any(grepl("Map", data_to_use[i,4]))){
        new_row <- c("Map", "Projections",54)
        df_stack2 <- rbind(df_stack2, new_row)
      }
      if(any(grepl("Data Visualization", data_to_use[i,4]))){
        new_row <- c("Data Visualization", "Projections",54)
        df_stack2 <- rbind(df_stack2, new_row)
      }
      if(any(grepl("Infographic", data_to_use[i,4]))){
        new_row <- c("Infographic", "Projections",54)
        df_stack2 <- rbind(df_stack2, new_row)
      }
    }
    #---permits---
    if (any(grepl("Permits", data_to_use[i,3]))) {
      if(any(grepl("Table", data_to_use[i,4]))){
        new_row <- c("Table", "Permits",54)
        df_stack2 <- rbind(df_stack2, new_row)
      }
      if(any(grepl("Table Download", data_to_use[i,4]))){
        new_row <- c("Table Download", "Permits",54)
        df_stack2 <- rbind(df_stack2, new_row)
      }
      if(any(grepl("Report", data_to_use[i,4]))){
        new_row <- c("Report", "Permits",54)
        df_stack2 <- rbind(df_stack2, new_row)
      }
      if(any(grepl("Map", data_to_use[i,4]))){
        new_row <- c("Map", "Permits",54)
        df_stack2 <- rbind(df_stack2, new_row)
      }
      if(any(grepl("Data Visualization", data_to_use[i,4]))){
        new_row <- c("Data Visualization", "Permits",54)
        df_stack2 <- rbind(df_stack2, new_row)
      }
      if(any(grepl("Infographic", data_to_use[i,4]))){
        new_row <- c("Infographic", "Permits",54)
        df_stack2 <- rbind(df_stack2, new_row)
      }
    }
    #----occupancy---
    if (any(grepl("Occupancy", data_to_use[i,3]))) {
      if(any(grepl("Table", data_to_use[i,4]))){
        new_row <- c("Table", "Occupancy",54)
        df_stack2 <- rbind(df_stack2, new_row)
      }
      if(any(grepl("Table Download", data_to_use[i,4]))){
        new_row <- c("Table Download", "Occupancy",54)
        df_stack2 <- rbind(df_stack2, new_row)
      }
      if(any(grepl("Report", data_to_use[i,4]))){
        new_row <- c("Report", "Occupancy",54)
        df_stack2 <- rbind(df_stack2, new_row)
      }
      if(any(grepl("Map", data_to_use[i,4]))){
        new_row <- c("Map", "Occupancy",54)
        df_stack2 <- rbind(df_stack2, new_row)
      }
      if(any(grepl("Data Visualization", data_to_use[i,4]))){
        new_row <- c("Data Visualization", "Occupancy",54)
        df_stack2 <- rbind(df_stack2, new_row)
      }
      if(any(grepl("Infographic", data_to_use[i,4]))){
        new_row <- c("Infographic", "Occupancy",54)
        df_stack2 <- rbind(df_stack2, new_row)
      }
    }
    #---housing units---
    if (any(grepl("Housing Units", data_to_use[i,3]))) {
      if(any(grepl("Table", data_to_use[i,4]))){
        new_row <- c("Table", "Housing Units",54)
        df_stack2 <- rbind(df_stack2, new_row)
      }
      if(any(grepl("Table Download", data_to_use[i,4]))){
        new_row <- c("Table Download", "Housing Units",54)
        df_stack2 <- rbind(df_stack2, new_row)
      }
      if(any(grepl("Report", data_to_use[i,4]))){
        new_row <- c("Report", "Housing Units",54)
        df_stack2 <- rbind(df_stack2, new_row)
      }
      if(any(grepl("Map", data_to_use[i,4]))){
        new_row <- c("Map", "Housing Units",54)
        df_stack2 <- rbind(df_stack2, new_row)
      }
      if(any(grepl("Data Visualization", data_to_use[i,4]))){
        new_row <- c("Data Visualization", "Housing Units",54)
        df_stack2 <- rbind(df_stack2, new_row)
      }
      if(any(grepl("Infographic", data_to_use[i,4]))){
        new_row <- c("Infographic", "Housing Units",54)
        df_stack2 <- rbind(df_stack2, new_row)
      }
    }    
    #---housing prices/rent---
    if (any(grepl("Housing Prices / Rent", data_to_use[i,3]))) {
      if(any(grepl("Table", data_to_use[i,4]))){
        new_row <- c("Table", "Housing Prices / Rent",54)
        df_stack2 <- rbind(df_stack2, new_row)
      }
      if(any(grepl("Table Download", data_to_use[i,4]))){
        new_row <- c("Table Download", "Housing Prices / Rent",54)
        df_stack2 <- rbind(df_stack2, new_row)
      }
      if(any(grepl("Report", data_to_use[i,4]))){
        new_row <- c("Report", "Housing Prices / Rent",54)
        df_stack2 <- rbind(df_stack2, new_row)
      }
      if(any(grepl("Map", data_to_use[i,4]))){
        new_row <- c("Map", "Housing Prices / Rent",54)
        df_stack2 <- rbind(df_stack2, new_row)
      }
      if(any(grepl("Data Visualization", data_to_use[i,4]))){
        new_row <- c("Data Visualization", "Housing Prices / Rent",54)
        df_stack2 <- rbind(df_stack2, new_row)
      }
      if(any(grepl("Infographic", data_to_use[i,4]))){
        new_row <- c("Infographic", "Housing Prices / Rent",54)
        df_stack2 <- rbind(df_stack2, new_row)
      }
    }
    #---housing characteristics---
    if (any(grepl("Housing Characteristics", data_to_use[i,3]))) {
      if(any(grepl("Table", data_to_use[i,4]))){
        new_row <- c("Table", "Housing Characteristics",54)
        df_stack2 <- rbind(df_stack2, new_row)
      }
      if(any(grepl("Table Download", data_to_use[i,4]))){
        new_row <- c("Table Download", "Housing Characteristics",54)
        df_stack2 <- rbind(df_stack2, new_row)
      }
      if(any(grepl("Report", data_to_use[i,4]))){
        new_row <- c("Report", "Housing Characteristics",54)
        df_stack2 <- rbind(df_stack2, new_row)
      }
      if(any(grepl("Map", data_to_use[i,4]))){
        new_row <- c("Map", "Housing Characteristics",54)
        df_stack2 <- rbind(df_stack2, new_row)
      }
      if(any(grepl("Data Visualization", data_to_use[i,4]))){
        new_row <- c("Data Visualization", "Housing Characteristics",54)
        df_stack2 <- rbind(df_stack2, new_row)
      }
      if(any(grepl("Infographic", data_to_use[i,4]))){
        new_row <- c("Infographic", "Housing Characteristics",54)
        df_stack2 <- rbind(df_stack2, new_row)
      }
    }    
    #---household type---
    if (any(grepl("Household Type", data_to_use[i,3]))) {
      if(any(grepl("Table", data_to_use[i,4]))){
        new_row <- c("Table", "Household Type",54)
        df_stack2 <- rbind(df_stack2, new_row)
      }
      if(any(grepl("Table Download", data_to_use[i,4]))){
        new_row <- c("Table Download", "Household Type",54)
        df_stack2 <- rbind(df_stack2, new_row)
      }
      if(any(grepl("Report", data_to_use[i,4]))){
        new_row <- c("Report", "Household Type",54)
        df_stack2 <- rbind(df_stack2, new_row)
      }
      if(any(grepl("Map", data_to_use[i,4]))){
        new_row <- c("Map", "Household Type",54)
        df_stack2 <- rbind(df_stack2, new_row)
      }
      if(any(grepl("Data Visualization", data_to_use[i,4]))){
        new_row <- c("Data Visualization", "Household Type",54)
        df_stack2 <- rbind(df_stack2, new_row)
      }
      if(any(grepl("Infographic", data_to_use[i,4]))){
        new_row <- c("Infographic", "Household Type",54)
        df_stack2 <- rbind(df_stack2, new_row)
      }
    }      
    #---household size---
    if (any(grepl("Household Size", data_to_use[i,3]))) {
      if(any(grepl("Table", data_to_use[i,4]))){
        new_row <- c("Table", "Household Size",54)
        df_stack2 <- rbind(df_stack2, new_row)
      }
      if(any(grepl("Table Download", data_to_use[i,4]))){
        new_row <- c("Table Download", "Household Size",54)
        df_stack2 <- rbind(df_stack2, new_row)
      }
      if(any(grepl("Report", data_to_use[i,4]))){
        new_row <- c("Report", "Household Size",54)
        df_stack2 <- rbind(df_stack2, new_row)
      }
      if(any(grepl("Map", data_to_use[i,4]))){
        new_row <- c("Map", "Household Size",54)
        df_stack2 <- rbind(df_stack2, new_row)
      }
      if(any(grepl("Data Visualization", data_to_use[i,4]))){
        new_row <- c("Data Visualization", "Household Size",54)
        df_stack2 <- rbind(df_stack2, new_row)
      }
      if(any(grepl("Infographic", data_to_use[i,4]))){
        new_row <- c("Infographic", "Household Size",54)
        df_stack2 <- rbind(df_stack2, new_row)
      }
    }      
    #---household income---
    if (any(grepl("Household Income", data_to_use[i,3]))) {
      if(any(grepl("Table", data_to_use[i,4]))){
        new_row <- c("Table", "Household Income",54)
        df_stack2 <- rbind(df_stack2, new_row)
      }
      if(any(grepl("Table Download", data_to_use[i,4]))){
        new_row <- c("Table Download", "Household Income",54)
        df_stack2 <- rbind(df_stack2, new_row)
      }
      if(any(grepl("Report", data_to_use[i,4]))){
        new_row <- c("Report", "Household Income",54)
        df_stack2 <- rbind(df_stack2, new_row)
      }
      if(any(grepl("Map", data_to_use[i,4]))){
        new_row <- c("Map", "Household Income",54)
        df_stack2 <- rbind(df_stack2, new_row)
      }
      if(any(grepl("Data Visualization", data_to_use[i,4]))){
        new_row <- c("Data Visualization", "Household Income",54)
        df_stack2 <- rbind(df_stack2, new_row)
      }
      if(any(grepl("Infographic", data_to_use[i,4]))){
        new_row <- c("Infographic", "Household Income",54)
        df_stack2 <- rbind(df_stack2, new_row)
      }
    }    
    #---foreclosures---
    if (any(grepl("Foreclosures", data_to_use[i,3]))) {
      if(any(grepl("Table", data_to_use[i,4]))){
        new_row <- c("Table", "Foreclosures",54)
        df_stack2 <- rbind(df_stack2, new_row)
      }
      if(any(grepl("Table Download", data_to_use[i,4]))){
        new_row <- c("Table Download", "Foreclosures",54)
        df_stack2 <- rbind(df_stack2, new_row)
      }
      if(any(grepl("Report", data_to_use[i,4]))){
        new_row <- c("Report", "Foreclosures",54)
        df_stack2 <- rbind(df_stack2, new_row)
      }
      if(any(grepl("Map", data_to_use[i,4]))){
        new_row <- c("Map", "Foreclosures",54)
        df_stack2 <- rbind(df_stack2, new_row)
      }
      if(any(grepl("Data Visualization", data_to_use[i,4]))){
        new_row <- c("Data Visualization", "Foreclosures",54)
        df_stack2 <- rbind(df_stack2, new_row)
      }
      if(any(grepl("Infographic", data_to_use[i,4]))){
        new_row <- c("Infographic", "Foreclosures",54)
        df_stack2 <- rbind(df_stack2, new_row)
      }
    }       
    #---estimates---
    if (any(grepl("Estimates", data_to_use[i,3]))) {
      if(any(grepl("Table", data_to_use[i,4]))){
        new_row <- c("Table", "Estimates",54)
        df_stack2 <- rbind(df_stack2, new_row)
      }
      if(any(grepl("Table Download", data_to_use[i,4]))){
        new_row <- c("Table Download", "Estimates",54)
        df_stack2 <- rbind(df_stack2, new_row)
      }
      if(any(grepl("Report", data_to_use[i,4]))){
        new_row <- c("Report", "Estimates",54)
        df_stack2 <- rbind(df_stack2, new_row)
      }
      if(any(grepl("Map", data_to_use[i,4]))){
        new_row <- c("Map", "Estimates",54)
        df_stack2 <- rbind(df_stack2, new_row)
      }
      if(any(grepl("Data Visualization", data_to_use[i,4]))){
        new_row <- c("Data Visualization", "Estimates",54)
        df_stack2 <- rbind(df_stack2, new_row)
      }
      if(any(grepl("Infographic", data_to_use[i,4]))){
        new_row <- c("Infographic", "Estimates",54)
        df_stack2 <- rbind(df_stack2, new_row)
      }
    }   
  }
  
  colnames(df_stack2) <- col_name
  
  bar1 <- ggplot(df_stack2, aes(x = sub, y = 1, fill = Tools)) +
    geom_col() +
    scale_fill_manual(values = cbPalette) +
    xlab("Sub-categories: Housing") +
    ylab("Counts") +
    theme(axis.text.x = element_text(angle = 45, hjust = 1),
          plot.title = element_text(size = 20, face = "bold", hjust = 0.5)) +
    ggtitle("Different type of tools inside each sub-category of Housing")
  
  # Set the plot margin to center the title
  bar1 + theme_minimal() +
    theme(plot.title.position = "plot", plot.margin = margin(30, 0, 30, 0)) + coord_flip()
}
```

```{r}
hous_sub_cat_and_tool("All Sample States and Territories")
```

```{r}
# Plot 3 - Geographic levels

housing$Geographic.Levels = tolower(housing$Geographic.Levels)

hous_geography_plot <- function(selected_state) {
  df_stack3 <- data.frame(
    geography = character()
  )
  col_name = c("Geography")
  colnames(df_stack3) <- col_name
  
  
  # Initialize variables to store the counts
  if (selected_state == "All Sample States and Territories"){
    data_to_use = housing
  }
  else{
    data_to_use = housing[housing$State..Country == selected_state,]
  }
  
  
  for (i in 1:nrow(data_to_use)) {
    if(any(grepl("alaska", data_to_use[i,7]))){
      new_row <- c("Alaska Native")
      df_stack3 <- rbind(df_stack3, new_row)}
    if (any(grepl("block", data_to_use[i,7]))) {
      new_row <- c("Block")
      df_stack3 <- rbind(df_stack3, new_row)}
    if (any(grepl("group", data_to_use[i,7]))) {
      new_row <- c("Block Group")
      df_stack3 <- rbind(df_stack3, new_row)}
    if (any(grepl("borough", data_to_use[i,7]))) {
      new_row <- c("Borough")
      df_stack3 <- rbind(df_stack3, new_row)}
    if (any(grepl("census", data_to_use[i,7]))) {
      new_row <- c("Census Area")
      df_stack3 <- rbind(df_stack3, new_row)}
    if (any(grepl("subarea", data_to_use[i,7]))) {
      new_row <- c("Census Subarea")
      df_stack3 <- rbind(df_stack3, new_row)}
    if (any(grepl("census designated place", data_to_use[i,7]))) {
      new_row <- c("Census Designated Place")
      df_stack3 <- rbind(df_stack3, new_row)}
    if (any(grepl("tract", data_to_use[i,7]))) {
      new_row <- c("Census Tract")
      df_stack3 <- rbind(df_stack3, new_row)}
    if (any(grepl("town", data_to_use[i,7]))) {
      new_row <- c("City/Town")
      df_stack3 <- rbind(df_stack3, new_row)}
    if (any(grepl("county", data_to_use[i,7]))) {
      new_row <- c("County")
      df_stack3 <- rbind(df_stack3, new_row)}
    if (any(grepl("subdivision", data_to_use[i,7]))) {
      new_row <- c("County Subdivision")
      df_stack3 <- rbind(df_stack3, new_row)}
    if (any(grepl("combined", data_to_use[i,7]))) {
      new_row <- c("Combined Statistical Area")
      df_stack3 <- rbind(df_stack3, new_row)}
    if (any(grepl("congressional", data_to_use[i,7]))) {
      new_row <- c("Congressional District")
      df_stack3 <- rbind(df_stack3, new_row)}
    if (any(grepl("development", data_to_use[i,7]))) {
      new_row <- c("Development District")
      df_stack3 <- rbind(df_stack3, new_row)}
    if (any(grepl("economic", data_to_use[i,7]))) {
      new_row <- c("Economic Region")
      df_stack3 <- rbind(df_stack3, new_row)}
    if (any(grepl("incorporated city", data_to_use[i,7]))) {
      new_row <- c("Incorporated City")
      df_stack3 <- rbind(df_stack3, new_row)}
    if (any(grepl("incorporated place", data_to_use[i,7]))) {
      new_row <- c("Incorporated Place")
      df_stack3 <- rbind(df_stack3, new_row)}
    if (any(grepl("jurisdiction", data_to_use[i,7]))) {
      new_row <- c("Jurisdiction")
      df_stack3 <- rbind(df_stack3, new_row)}
    if (any(grepl("legislative", data_to_use[i,7]))) {
      new_row <- c("Legislative District")
      df_stack3 <- rbind(df_stack3, new_row)}
    if (any(grepl("metropolitan", data_to_use[i,7]))) {
      new_row <- c("Metropolitan Area")
      df_stack3 <- rbind(df_stack3, new_row)}
    if (any(grepl("micropolitan", data_to_use[i,7]))) {
      new_row <- c("Micropolitan Area")
      df_stack3 <- rbind(df_stack3, new_row)}
    if (any(grepl("municipality", data_to_use[i,7]))) {
      new_row <- c("Municipality")
      df_stack3 <- rbind(df_stack3, new_row)}
    if (any(grepl("nation", data_to_use[i,7]))) {
      new_row <- c("Nation")
      df_stack3 <- rbind(df_stack3, new_row)}
    if (any(grepl("native", data_to_use[i,7]))) {
      new_row <- c("Native Village Statistical Area")
      df_stack3 <- rbind(df_stack3, new_row)}
    if (any(grepl("corporation", data_to_use[i,7]))) {
      new_row <- c("Native Regional Corporation")
      df_stack3 <- rbind(df_stack3, new_row)}
    if (any(grepl("neighborhood", data_to_use[i,7]))) {
      new_row <- c("Neighborhood Cluster")
      df_stack3 <- rbind(df_stack3, new_row)}
    if (any(grepl("parish", data_to_use[i,7]))) {
      new_row <- c("Parish")
      df_stack3 <- rbind(df_stack3, new_row)}
    if (any(grepl("places", data_to_use[i,7]))) {
      new_row <- c("Place")
      df_stack3 <- rbind(df_stack3, new_row)}
    if (any(grepl("prosperity", data_to_use[i,7]))) {
      new_row <- c("Prosperity Region")
      df_stack3 <- rbind(df_stack3, new_row)}
    if (any(grepl("puma", data_to_use[i,7]))) {
      new_row <- c("Public Use Microdata Area")
      df_stack3 <- rbind(df_stack3, new_row)}
    if (any(grepl("school", data_to_use[i,7]))) {
      new_row <- c("School District")
      df_stack3 <- rbind(df_stack3, new_row)}
    if (any(grepl("region", data_to_use[i,7]))) {
      new_row <- c("Region")
      df_stack3 <- rbind(df_stack3, new_row)}
    if (any(grepl("state", data_to_use[i,7]))) {
      new_row <- c("State")
      df_stack3 <- rbind(df_stack3, new_row)}
    if (any(grepl("substate", data_to_use[i,7]))) {
      new_row <- c("Substate Region")
      df_stack3 <- rbind(df_stack3, new_row)}
    if (any(grepl("summary", data_to_use[i,7]))) {
      new_row <- c("Summary Level")
      df_stack3 <- rbind(df_stack3, new_row)}
    if (any(grepl("township", data_to_use[i,7]))) {
      new_row <- c("Township")
      df_stack3 <- rbind(df_stack3, new_row)}
    if (any(grepl("urbanized", data_to_use[i,7]))) {
      new_row <- c("Urbanized Area")
      df_stack3 <- rbind(df_stack3, new_row)}
    if (any(grepl("rural", data_to_use[i,7]))) {
      new_row <- c("Urban/Rural")
      df_stack3 <- rbind(df_stack3, new_row)}
    if (any(grepl("village", data_to_use[i,7]))) {
      new_row <- c("Village")
      df_stack3 <- rbind(df_stack3, new_row)}
    if (any(grepl("ward", data_to_use[i,7]))) {
      new_row <- c("Ward")
      df_stack3 <- rbind(df_stack3, new_row)}
    if (any(grepl("zcta", data_to_use[i,7]))) {
      new_row <- c("ZCTA")
      df_stack3 <- rbind(df_stack3, new_row)}
    if (any(grepl("zip", data_to_use[i,7]))) {
      new_row <- c("Zip Code")
      df_stack3 <- rbind(df_stack3, new_row)}
  }
  colnames(df_stack3) <- col_name 
  geography_types <- df_stack3 %>% group_by(Geography)%>%
    summarise(count = n())
  
  
  ggplot(geography_types, aes(x = Geography, y = count)) +
    geom_col(width=.8) +
    scale_fill_manual(values = cbPalette) +
    labs(x="Geography: Demographics", y="Counts") + 
    theme_minimal() + theme(axis.text.x = element_text(angle = 45, hjust = 1),
          plot.title = element_text(hjust = 0.4, face = "bold")) +coord_flip()+
    ggtitle("Types of Geographic Levels") 
}

hous_geography_plot("All Sample States and Territories")
```

```{r}
hous_direct_census_link <- function(selected_state, data_table) {
  if (selected_state == "All Sample States and Territories") {
    data_to_use <- data_table
  } else {
    data_to_use <- data_table[data_table$State..Country == selected_state, ]
  }
  
  count_result <- data_to_use %>% group_by(Direct.links.to.Census) %>% summarize(count = n())
  colnames(count_result) <- c("direct link", "count")
  count_result <- count_result[count_result$`direct link` != "", ]
  
  sorted_df <- count_result[order(-count_result$count), ]
  
  # Replace "N" with "No" and "Y" with "Yes"
  sorted_df$`direct link` <- ifelse(sorted_df$`direct link` == "N", "No", "Yes")
  
  # Adding a title to the pie graph
  title <- paste("Data Census Link Distribution \n in", selected_state)
  
  par(mfrow = c(1, 1), mar = c(4, 4, 2, 2))
  pie(sorted_df$count, labels = sorted_df$`direct link`, border = "white", col = cbPalette, cex = 1, main = title)
}

hous_direct_census_link("All Sample States and Territories", housing)
```

```{r}
hous_historical_data <- function(selected_state, data_table) {
  if (selected_state == "All Sample States and Territories") {
    data_to_use <- data_table
  } else {
    data_to_use <- data_table[data_table$State..Country == selected_state, ]
  }
  
  count_result <- data_to_use %>% group_by(Historical.data) %>% summarize(count = n())
  colnames(count_result) <- c("historical data", "count")
  count_result <- count_result[count_result$`historical data` != "", ]
  count_result <- count_result[count_result$`historical data` != "N/A", ]
  
  sorted_df <- count_result[order(-count_result$count), ]
  
  # Replace "N" with "No" and "Y" with "Yes"
  sorted_df$`historical data` <- ifelse(sorted_df$`historical data` == "N", "No", "Yes")
  
  # Adding a title to the pie graph
  title <- paste("Historical Data Distribution \n in", selected_state)
  
  par(mfrow = c(1, 1), mar = c(4, 4, 2, 2))
  pie(sorted_df$count, labels = sorted_df$`historical data`, border = "white", col = cbPalette, cex = 1, main = title)
}

hous_historical_data("All Sample States and Territories", housing)
```

