---
title: "American Soldier Timeline"
author: "Chase Dawson"
date: "8/2/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(r2d3)
library(readr)
```

```{r}
# load data
dates <- read_csv(here::here("src", "timeline", "dates.csv"))
bars = c(10, 20, 30)
```

```{d3 data=dates, out.width="100%"}

var vw = width;
var vh = height;

var minDate, maxDate, xScale, xAxis, drawArea;
var startX = 0;
        
var margin = {
    top: 20, 
    bottom: 20, 
    left: 50, 
    right: 50,
};

var cv_Y = margin.top; 
var mi_Y = height - margin.bottom; 
var in_Y = (cv_Y + mi_Y)/2;

var groups = {
    CIVIL_RIGHTS: "Civil Rights",
    MILITARY: "Military",
    INTERSECTION: "Intersection"
};
        
function reformatData() {
    var startDates = data.map(d => {
        var date = new Date(d['Date']);
        return date;
    }); 

    var endDates = data.map(d => {
        var date = new Date(d['End']);
        return date;
    });
    
    minDate = new Date(Math.min(...startDates));
    maxDate = new Date(Math.max(...endDates));
}

function draw() {
  reformatData();   
  
  xScale = d3.scaleTime()
      .domain([minDate, maxDate])
      .range([margin.left, draw_width - margin.right]);
  
  xAxis = svg.append('g')
      .attr("transform", `translate(0, ${30})`)
      .call(d3.axisTop(xScale));
  
  d3.select('.xAxis')
      .selectAll("text")
      .style('font-size', '20px');
  
  drawArea = svg.append('g');
}

function drawCircles() {
  var circles = drawArea.selectAll("circle")
      .data(data);

  circles.enter().append("circle")
      .merge(circles)
      .attr("cx", (d) => {
              var x = xScale(new Date(d["Date"]));
              return x;
          })
          .attr("cy", (d) => {
              var group = d['Group'];
              var y;
              switch(group) {
                  case groups.CIVIL_RIGHTS:
                      y = cv_Y;
                      break;
                  case groups.MILITARY:
                      y = mi_Y;
                      break;
                  case groups.INTERSECTION:
                      y = in_Y;
                      break;
              };
              return y;
          })
          .attr("r", (d) => {
              var r = 10;
              return r;
          });
}

draw();
```
