---
title: "Call Loads by Time of Day"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(dplyr)
library(lubridate)
library(ggplot2)
library(plotly)
library(here)
library(stringr)

#source(here::here("src", "Profiling", "joining_albemarle_charlottesville.R"))
new_ems_data <- readr::read_csv(here("data", "final", "ems_clean_data.csv"))
```

```{r include = FALSE}
new_ems_data <- new_ems_data %>%
  ## Breaking down time of day info
  mutate(psap_time_of_day = ymd_hms(paste("2020-01-01", strftime(incident_psap_call_date_time, format="%H:%M:%S"), sep = " ")),
         psap_hour = hour(psap_time_of_day),
         psap_minute = minute(psap_time_of_day)) %>%
  ## Categorizing primary impressions manually:
  mutate(primary_impression_category = case_when(str_detect(situation_provider_primary_impression_code_and_description, "alcohol") ~ "Abuse of Alcohol",
                                                 str_detect(situation_provider_primary_impression_code_and_description, "abuse") ~ "Abuse of Substance",
                                                 str_detect(situation_provider_primary_impression_code_and_description, "allergic") ~ "Allergic Reaction",
                                                 str_detect(situation_provider_primary_impression_code_and_description, "ob") ~ "OB",
                                                 str_detect(situation_provider_primary_impression_code_and_description, "endocrine") ~ "Endocrine",
                                                 str_detect(situation_provider_primary_impression_code_and_description, "gi") ~ "GI/GU",
                                                 str_detect(situation_provider_primary_impression_code_and_description, " - ") ~ str_extract(situation_provider_primary_impression_code_and_description, "[^-]+"), 
                                                 !str_detect(situation_provider_primary_impression_code_and_description, " - ") ~ str_extract(situation_provider_primary_impression_code_and_description, "[^\\(]+")),
         primary_impression_category = trimws(primary_impression_category))
```

```{r include = FALSE}
top_impressions <- new_ems_data %>% 
  filter(!is.na(situation_provider_primary_impression_code_and_description)) %>%
  group_by(situation_provider_primary_impression_code_and_description) %>% 
  count() %>% 
  ungroup() %>%
  top_n(5) %>%
  arrange(desc(n))

top_impressions <- top_impressions$situation_provider_primary_impression_code_and_description

top_impression_categories <- new_ems_data %>% 
  filter(!is.na(primary_impression_category)) %>%
  group_by(primary_impression_category) %>% 
  count() %>% 
  ungroup() %>%
  top_n(10) %>%
  arrange(desc(n))

top_impression_categories <- top_impression_categories$primary_impression_category
```

Start with a baseline call load density for various impression categories:

```{r}
new_ems_data %>%
  filter(!is.na(situation_provider_primary_impression_code_and_description), 
         !is.na(psap_time_of_day), 
         primary_impression_category %in% top_impression_categories) %>%
  ggplot() +
  geom_density(aes(x = psap_time_of_day, color = primary_impression_category), alpha = 0.3) +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45))
```

Some evidence of changes in call load pre/post COVID. But it seems to be more driven by alcohol related incidents rather than overall changes:

```{r}
new_ems_data %>% 
  mutate(is_recent = ifelse(incident_date > "2020-03-01", "Post 03/01/2020", "Pre 03/01/2020")) %>%
  filter(!is.na(situation_provider_primary_impression_code_and_description), 
         !is.na(psap_time_of_day), 
         primary_impression_category %in% top_impression_categories) %>%
  group_by(is_recent) %>%
  ggplot() +
  geom_density(aes(x = psap_time_of_day, color = primary_impression_category), alpha = 0.3) +
  theme_minimal() +
  facet_grid(is_recent ~ .) +
  theme(axis.text.x = element_text(angle = 45),
        legend.position = "none")
```

```{r}

new_ems_data %>%
  filter(!is.na(situation_provider_primary_impression_code_and_description), 
         !is.na(psap_time_of_day), 
         primary_impression_category %in% top_impression_categories) %>%
  ## Can include this stuff if you want to facet by agency
  # group_by(agency_name) %>%
  # mutate(n = n()) %>%
  # filter(n > 1000) %>%
  ggplot() +
  geom_density(aes(x = psap_time_of_day, color = primary_impression_category), alpha = 0.3) +
  theme_minimal() +
  # facet_grid(~agency_name) +
  theme(axis.text.x = element_text(angle = 45))

```

```{r}
## ONLY WORKS ON UNIT LEVEL DATA
# cbPalette <- c("#999999", "#E69F00", "#56B4E9", "#009E73", "#F0E442", "#0072B2", "#D55E00", "#CC79A7", "#000000")
# 
# plot_data <- new_ems_data %>%
#   filter(!is.na(agency_name), 
#          !is.na(psap_time_of_day),
#          !str_detect(agency_name, "Test")) 
# 
# ggplot(plot_data) +
#   geom_density(aes(x = psap_time_of_day, fill = agency_name, color = agency_name), alpha = 0.2, position = "identity") +
#   #scale_color_manual(values = cbPalette) +
#   #scale_fill_manual(values = cbPalette) +
#   #facet_grid(agency_name ~ .) +
#   #scale_x_datetime(date_breaks = "2 hour", labels = format("%H:%M")) +
#   coord_cartesian(xlim = c(as.POSIXct("2020-01-01 01:00:00", tz = "UTC"), as.POSIXct("2020-01-01 22:00:00", tz = "UTC"))) +
#   labs(title = "Call Density Across Day", y = "", x = "Time of Day") +
#   theme_minimal() +
#   theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1),
#         axis.text.y = element_blank(),
#         strip.text = element_blank(),
#         legend.position = "none")
```










