---
title: "Presentation Notes"
description: "Quick Notes for Presentation"
weight: 4
draft: false
output: html_document
---

```{r, echo = FALSE}
# setup
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE, fig.width = 15, fig.height = 10, progress = FALSE)

```

```{r}
load(here::here("data", "working", "model_objects", "basic_model_bayes_no_interact.RData"))
load(here::here("data", "working", "model_objects", "basic_model_bayes_yes_interact.RData"))
load(here::here("data", "working", "model_objects", "basic_model_freq_no_interact.RData"))
load(here::here("data", "working", "model_objects", "basic_model_freq_yes_interact.RData"))
load(here::here("data", "working", "model_objects", "neighbor_model_bayes_no_interact.RData"))
load(here::here("data", "working", "model_objects", "neighbor_model_bayes_yes_interact.RData"))

load(here::here("data", "working", "model_objects", "local_morans_statistic.RData"))

library(rstanarm)
library(bayesplot)
library(dplyr)
library(ggplot2)
library(sf)
library(broom)
library(broom.mixed)
library(purrr)
library(glue)
library(stringr)
library(viridis)
library(spdep)
library(ape)
library(leaflet)
library(leaflet.mapboxgl)
library(ggthemes)
library(tidyr)
library(glue)
library(here)
library(lubridate)
library(tidycensus)

prepared_data <- readr::read_csv(here::here("data", "final", "response_time_model_data_prepared.csv"))
prepared_data_sp <- sf::st_read(here::here("data", "final", "response_time_model_data_prepared_sp.geojson"), quiet = TRUE)


freq_models <- list("basic_model_freq_no_interact" = basic_model_freq_no_interact,
                    "basic_model_freq_yes_interact" = basic_model_freq_yes_interact)

bayes_models <- stanreg_list("basic_model_bayes_no_interact" = basic_model_bayes_no_interact,
                             "basic_model_bayes_yes_interact" = basic_model_bayes_yes_interact,
                             "neighbor_model_bayes_no_interact" = neighbor_model_bayes_no_interact,
                             "neighbor_model_bayes_yes_interact" = neighbor_model_bayes_yes_interact)



bayes_model_coefs <- map(bayes_models, ~tidy(.x$stanfit,
                                             estimate.method = "median",
                                             conf.int = TRUE,
                                             conf.level = 0.95)) %>%
  map(~filter(.x, !(term %in% c("sigma", "mean_PPD", "log-posterior"))))


bayes_model_coefs_trans <- bayes_model_coefs %>%
  map(~mutate(.x, across(c(estimate,
                           conf.low,
                           conf.high),
                         list(scale_factor = ~exp(.x * (.x != .x[1])),
                              time_to_incident = ~exp(.x * (.x != .x[1]) + .x[1])))))


bayes_residuals <- map(bayes_models, residuals)

augmented_data <- prepared_data_sp %>% 
  mutate(resid_basic_no = bayes_residuals$basic_model_bayes_no_interact,
         resid_basic_yes = bayes_residuals$basic_model_bayes_yes_interact,
         resid_neighbor_no = bayes_residuals$neighbor_model_bayes_no_interact,
         resid_neighbor_yes = bayes_residuals$neighbor_model_bayes_yes_interact)

cbbPalette <- c("#E69F00", "#56B4E9", "#009E73", "#F0E442", "#0072B2", "#D55E00", "#CC79A7")

term_dictionary <- tribble(~term, ~term_pretty,
                           "time_of_day", "Time of Day",
                           "response_vehicle_type_collapsedother", "Vehicle Type: Other",
                           "response_vehicle_type_collapsedmissing", "Vehicle Type: Missing",
                           "response_vehicle_type_collapsedfire apparatus", "Vehicle Type: Fire Apparatus",
                           "possible_impression_category_collapsedrespiratory", "Symptom Type: Respiratory",
                           "possible_impression_category_collapsedpain", "Symptom Type: Pain",
                           "possible_impression_category_collapsedother", "Symptom Type: Other",
                           "possible_impression_category_collapsedbehavioral", "Symptom Type: Behavioral",
                           "possible_impression_category_collapsedneuro", "Symptom Type: Neuro",
                           "possible_impression_category_collapsedmissing", "Symptom Type: Missing",
                           "possible_impression_category_collapsedinjury", "Symptom Type: Injury",
                           "possible_impression_category_collapsedinfectious", "Symptom Type: Infectious",
                           "possible_impression_category_collapsedgi/gu", "Symptom Type: GI/GU",
                           "possible_impression_category_collapsedendocrine", "Symptom Type: Endocrine",
                           "possible_impression_category_collapsedcv", "Symptom Type: Cardiovascular",
                           "patient_gendermissing", "Patient Gender: Missing or Unknown",
                           "patient_gendermale", "Patient Gender: Male",
                           "patient_first_race_collapsedwhite", "Patient Race: White",
                           "patient_first_race_collapsedother", "Patient Race: Other",
                           "patient_first_race_collapsedmissing", "Patient Race: Missing",
                           "patient_age", "Patient Age",
                           "after_covidTRUE", "During Covid-19",
                           "(Intercept)", "Intercept")


#sf_map_colors <- c('#7b3294','#c2a5cf','#d7d7d7','#a6dba0','#008837') 
#sf_map_colors <- c("#a52748", "#e47961", "#ffffe0",'#579eb9','#1c5796') 
sf_map_colors <- rev(c("#cc415a", "#ed9ab1", "#EBE8E8",'#92b2df','#2f75b3'))


theme_set(theme_minimal() +
            theme(plot.title = element_text(hjust = 0.5, color = "gray10", size = 22),
                  plot.subtitle = element_text(hjust = 0.5, color = "gray30", face = "italic", size = 18),
                  axis.title = element_text(size = 18, color = "gray10"),
                  axis.text = element_text(size = 16, color = "gray30"),
                  strip.text = element_text(size = 20, color = "gray30"),
                  panel.spacing = unit(4, "lines"),
                  legend.key.size = unit(3, "line"),
                  legend.text = element_text(size = 14, color = "gray30"),
                  legend.title = element_text(size = 20, color = "gray10")))

options(mapbox.accessToken = Sys.getenv("MAPBOX_TOKEN"))

# fixing after covid coefs
neighbor_coef_df <- as.data.frame(neighbor_model_bayes_yes_interact)


fixed_coefs <- neighbor_coef_df %>% 
  map2_df(.x = .[3:22], .y = .[23:42], .f = ~(.x + .y + neighbor_coef_df$after_covidTRUE)) %>% 
  mutate(across(everything(), exp)) %>% 
  rename_all(~paste0("after_covidTRUE:", .x)) %>% 
  pivot_longer(everything(), names_to = "term") %>% 
  group_by(term) %>% 
  summarise(across(value, 
                   .fns = list(estimate = median, 
                               conf.low = ~quantile(.x, probs = 0.05), 
                               conf.high = ~quantile(.x, probs = 0.95)),
                   .names = "{fn}_scale_factor"),
            .groups = "drop")

bayes_model_coefs_trans$neighbor_model_bayes_yes_interact <- bayes_model_coefs_trans$neighbor_model_bayes_yes_interact %>% 
  filter(!str_detect(term, "after_covidTRUE")) %>% 
  bind_rows(fixed_coefs)
```


## Has COVID-19 Exacerbated Existing Healthcare Disparities in Charlottesville and Albemarle County Emergency Medical Services?

<br>
<br>
<br>
<br>
<br>

```{r}
library(ggalt)
## Vitals data categorized

vital = read.csv(here('data','original','vital_stats','Death_dataset_from_2016_to_YTD.csv'))
vital$RACE = factor(vital$RACE,
                    levels = c(1:11,15,21,22,24,99),
                    labels = c('White', "Black", 'Amer. Indian', rep("Asian",7),
                               "Native Hawaiian", "Other", rep("Other", 4)))
vital = vital %>% 
  mutate(DATE_OF_DEATH = mdy(DATE_OF_DEATH))

 

cutoff = as.Date("2020-03-15")
vital = vital %>%
  mutate(covid = DATE_OF_DEATH>= cutoff )

 

firt = str_sub(vital$CAUSE_OF_DEATH, 1,3) 

 


category = vector(length = length(firt))
#ICD 10 CODEBOOK
category = case_when(
  grepl("^A|^B", firt) ~ "Certain Infectious Diseases",
  grepl("^C|^D0|^D1|^D2|^D3|^D4", firt) ~ "Neoplasms",
  grepl("^D5|^D6|^D7|^D8", firt) ~ "Diseases of the Blood",
  grepl("^E", firt) ~ "Endocrine, Nutritional, Metabolic Disease",
  grepl("^F", firt) ~ "Mental, Behavioural, Neurodev. Disease",
  grepl("^G", firt) ~ "Nervous System",
  grepl("^H0|^H1|^H2|^H3|^H4|^H5", firt) ~ "Eye/ Adnexa Disease",
  grepl("^H6|^H7|^H8|^H9", firt) ~ "Ear/ Mastoid Disease",
  grepl("^I", firt) ~ "Circulatory System",
  grepl("^J", firt) ~ "Respiratory System",
  grepl("^K", firt) ~ "Digestive System",
  grepl("^L", firt) ~ "Skin Tissue Disease",
  grepl("^M", firt) ~ "Muscoskeletal/ Connective Tissue",
  grepl("^N", firt) ~ "Genitourinary System",
  grepl("^O", firt) ~ "Pregnancy/ Childbirth/ Puerperium",
  grepl("^P", firt) ~ "Perinatal Period Complications",
  grepl("^Q", firt) ~ "Congenital Malformations/Chromsomal Abnormalities",
  grepl("^R", firt) ~ "Unclassified Abnormalities",
  grepl("^S|^T", firt) ~ "Injury/ Poisoning/ Consequences of Extenral Causes",
  grepl("^V|^W|^X|^Y", firt) ~ "External Causes of Morbidity",
  grepl("^Z", firt) ~ "Factors Influencing Healthcare Access"
)


 

vital$category = category

 

my_cols <-  c("#E69F00", "#56B4E9", "#009E73", "#F0E442", "#0072B2", "#D55E00", "#CC79A7")
cbbPalette <- c("#E69F00", "#56B4E9", "#009E73", "#F0E442", "#0072B2", "#D55E00", "#CC79A7")


 tots = vital %>% 
  filter(RACE %in% c('White','Black')) %>%
  count(RACE)
all_cat_death_tots = vital %>%
  filter(RACE %in% c('White','Black')) %>%
  group_by(RACE)%>%
  count(category, sort = T)
calc_relative_risk = function(death_cat){
  cat_death = all_cat_death_tots %>%
    filter(category == death_cat) %>%
    select(n) %>%
    summarise_all(funs(sum))
  risk = cat_death/tots 
  risk = risk %>%
    select(n)
  relative_risk = risk[2,]/risk[1,]
}
relative_risk = data.frame()
for( i in unique(na.omit(vital$category))){
  relative_risk = rbind(relative_risk, c(i,calc_relative_risk(i)))
}
colnames(relative_risk) = c('category','relative_risk')
relative_risk[,2] <- as.numeric(relative_risk[,2])
relative_risk$white_risk = 1
relative_risk = relative_risk %>%
  arrange(desc(relative_risk))
relative_risk$category = factor(relative_risk$category, levels = rev(relative_risk$category))

relative_risk %>%
  ggplot(aes(x=white_risk, xend=relative_risk, y=category)) +
  geom_segment(aes(x=white_risk,
                   xend=relative_risk,
                   y=category,
                   yend=category),
               color=cbbPalette[1], size=1.5)+
  geom_dumbbell(color=cbbPalette[1],
                size_x = 0,
                size_xend = 5,
                #Note: there is no US:'color' for UK:'colour'
                # in geom_dumbbel unlike standard geoms in ggplot()
                colour_x=cbbPalette[1],
                colour_xend = cbbPalette[5])+
  scale_x_log10() +
  labs(x="Relative Risk", y="ICD 10 Code",
       title="Relative Risk of Death", subtitle = "Black Patients vs. White Patients\n") +
  theme(axis.title.y = element_blank(),
        plot.margin = margin(0, 4, 0, 0, unit = "cm"))
```
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>


## Call Volume

```{r, results = "hide"}
city_border <- tigris::counties(state = "VA",
                                cb = TRUE, year = 2018, class = "sf") %>%
  filter(COUNTYFP == 540) %>%
  st_transform(crs = 4326)

ems_clean_data <- readr::read_csv(here("data", "final", "ems_clean_data.csv"))

county_tracts_sp <- tigris::tracts(state = "VA", county = c("albemarle"),
                                   cb = TRUE, year = 2018, class = "sf") %>%
  st_transform(crs = 4326) %>%
  select(NAME)

neighborhoods_sp <- st_read(here("data", "original", "neighborhoods", "planning_area_06_04_2020.shp"),
                            quiet = TRUE) %>%
  st_transform(crs = 4326) %>%
  select(NAME)

county_neighborhoods_sp <- bind_rows(county_tracts_sp,
                                     neighborhoods_sp)

ems_clean_data_sp <- ems_clean_data %>%
  filter(!is.na(scene_gps_latitude), !is.na(scene_gps_longitude)) %>%
  st_as_sf(coords = c("scene_gps_longitude", "scene_gps_latitude"), remove = FALSE, crs = 4326)

joined <- st_join(county_neighborhoods_sp, ems_clean_data_sp, join = st_contains)

period <- ymd("2020-03-15")
pre_period <- joined %>%
  filter(incident_date < period)

post_period <- joined %>%
  filter(incident_date >= period)

days_pre <- as.numeric(range(pre_period$incident_date)[2] - range(pre_period$incident_date)[1])
days_post <- as.numeric(range(post_period$incident_date)[2] - range(post_period$incident_date)[1] )

pre_daily <- pre_period %>%
  group_by(NAME) %>%
  summarize(daily_pre = n() / days_pre, .groups = "drop")

post_daily <- post_period %>%
  group_by(NAME) %>%
  summarize(daily_post = n() / days_post, .groups = "drop")

volume_change <- pre_daily %>%
  st_drop_geometry() %>%
  left_join(post_daily, ., by = "NAME") %>%
  mutate(change_ratio = daily_post / daily_pre)
```

```{r, fig.height = 6}
color_pal <- c('#762a83','#af8dc3','#e7d4e8','#f7f7f7','#d9f0d3')
sf_map_colors <- rev(c("#ed9ab1", "#EBE8E8",'#92b2df', "#2f75b3", "#163670"))

color_scale <- colorBin(sf_map_colors, 100 * c(0, 1.5), 100 * c(0.1, 0.35, 0.65, 0.90, 1.10, 1.3))

volume_change %>%
  mutate(change_ratio = change_ratio * 100) %>%
  leaflet(width = "100%") %>%
  addMapboxGL(style = "mapbox://styles/mapbox/light-v9") %>%
  addPolygons(color = "#444444", weight = 0.5, smoothFactor = 0.5,
              opacity = 1.0, fillOpacity = 0.7,
              fillColor = ~color_scale(change_ratio),
              label = ~map(glue("<strong>{NAME}</strong><br/>
                                Percentage of Regular Call Volume: {round(change_ratio, 2)}%"), htmltools::HTML)) %>%
  addPolygons(data = city_border,
              color = "#222222", weight = 3, smoothFactor = 0.5,
              fill = NA) %>%
  addLegend("bottomright", pal = color_scale, values = ~change_ratio,
            title = htmltools::HTML("Percentage of Regular Call Volume During COVID-19"),
            opacity = .8,
            labFormat = labelFormat(suffix = "%", between = " to "))
```

<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>


## Response Time Modeling

<br>

```{r}
bayes_model_coefs_trans$neighbor_model_bayes_yes_interact %>%
  mutate(after_covid = str_detect(term, "(after_covidTRUE.*)")) %>%
  mutate(term = str_replace(term, "after_covidTRUE:", "")) %>%
  filter(!str_detect(term, r"(Sigma|b\[)")) %>% 
  left_join(term_dictionary, by = "term") %>% 
  filter(term_pretty != "Intercept") %>% 
  mutate(term_group = ifelse(str_detect(term, "patient"), 
                        " ", ifelse(str_detect(term, "possible"),
                                                       "  ",
                                                       ifelse(str_detect(term, "vehicle"),
                                                              "   ",
                                                              "    ")))) %>% 
  ggplot(aes(y = reorder(term_pretty, estimate_scale_factor), color = after_covid)) +
  geom_point(aes(x = estimate_scale_factor), size = 2.2) +
  geom_errorbar(aes(xmin = conf.low_scale_factor, xmax = conf.high_scale_factor), size = 1.1) +
  scale_color_manual(values = cbbPalette, labels = c("Before Covid-19", "During Covid-19")) +
  coord_cartesian(xlim = c(0.7, 1.3)) +
  geom_vline(xintercept = 1, alpha = 0.5) +
  labs(y = NULL, 
       x = glue("Scale Factor Compared to Reference Incident"),
       color = NULL,
       title = "Neighborhood Level Model Coefficients",
       caption = "Before Covid-19 is considered to be before Febuary 15th. Point estimates are median estimates.\nIntervals are 95% credible intervals.") +
  theme(legend.position = "bottom") +
  facet_grid(term_group ~ ., 
             scales = "free_y",
             space = "free_y")
```
<br>


### Coefficient Map

```{r, fig.height=6}

sf_map_colors <- rev(c("#cc415a", "#ed9ab1", "#EBE8E8",'#92b2df','#2f75b3'))

map_colors <- colorBin(sf_map_colors, c(0.5, 2), c(0.65, 0.8, .95, 1.05, 1.30, 1.8))

bayes_model_coefs_trans$neighbor_model_bayes_yes_interact %>%
  mutate(term = str_replace(term, "after_covidTRUE:", "")) %>%
  filter(str_detect(term, r"(b\[)")) %>% 
  filter(!str_detect(term, "NEW_NAME")) %>% 
  mutate(term_pretty = str_replace(term, r"(b\[\(Intercept\) NAME:)", "")) %>%
  mutate(term_pretty = str_replace(term_pretty, r"(\])", "")) %>% 
  mutate(term_pretty = str_replace_all(term_pretty, r"(_)", " ")) %>% 
  mutate(NAME = term_pretty) %>% 
  mutate(term_pretty = str_replace(term_pretty, r"((\d\d\d))", r"(Census Tract \1)")) %>% 
  select(term_pretty, everything()) %>% 
  inner_join(prepared_data_sp, ., by = "NAME") %>% 
  group_by(NAME) %>% 
  slice_head(n = 1) %>% 
  ungroup() %>% 
  leaflet(width = "100%") %>% 
  addMapboxGL(style = "mapbox://styles/mapbox/light-v9") %>%
  addPolygons(color = "#444444", weight = 1, smoothFactor = 0.5,
    opacity = 1.0, fillOpacity = 0.5,
    fillColor = ~map_colors(estimate_scale_factor),
    label = ~map(glue("{term_pretty}<br/>
                      Scale Factor Estimate: {round(estimate_scale_factor, 2)}<br/>
                      95% Credible Interval: ({round(conf.low_scale_factor, 2)}, {round(conf.high_scale_factor, 2)})"), htmltools::HTML)) %>% 
  addLegend("bottomright", pal = map_colors, values = ~estimate_scale_factor,
            title = htmltools::HTML("Response Time Scale Factor<br/>From Reference Case"),
            opacity = .8)
```

<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>

## COVID-19 Indicator

```{r, fig.height=6, results = "hide"}
source(here::here("src", "Profiling", "create_covid_indicator.R"))

# load neighborhoods
city_neighborhoods <- st_read(here::here("data", "working", "neighborhood_demographics.geojson")) %>%
  rename(total_population_estimate = n) %>%
  select(c("NAME", "total_population_estimate", "geometry"))
# filter ems data to cases with non-NA gps data

# load census tract geometries and population estimates for the county
acs_total_pop_tract <- get_acs(geography = "tract",
                               year = 2018,
                               variables = c(total_population = "DP05_0001"),
                               state = "VA",
                               county = c("albemarle")) %>%
  pivot_wider(names_from = variable,
              values_from = c(estimate, moe),
              names_glue = "{variable}_{.value}")

acs_total_pop_tract_sp <- tigris::tracts(state = "VA", county = c("albemarle"),
                                         cb = TRUE, year = 2018, class = "sf") %>%
  st_transform(crs = 4326) %>%
  left_join(acs_total_pop_tract, by = "GEOID")

county_census_tracts <- acs_total_pop_tract_sp %>%
  select(c("NAME.y", "total_population_estimate", "geometry")) %>%
  rename(NAME = NAME.y)

geometries <- rbind(city_neighborhoods, county_census_tracts)

ems_full_sp <- ems %>%
  distinct %>%
  filter(!is.na(scene_gps_latitude), !is.na(scene_gps_longitude)) %>%
  st_as_sf(coords = c("scene_gps_longitude", "scene_gps_latitude"), remove = FALSE, crs = 4326)

city_border <- tigris::counties(state = "VA", cb = TRUE, year = 2018, class = "sf") %>%
  filter(COUNTYFP == 540) %>%
  st_transform(crs = 4326)

joined <- st_join(geometries, ems_full_sp, join = st_contains)
total_days <- as.numeric(range(ems_full_sp$incident_date)[2] - range(ems_full_sp$incident_date)[1])

cutoff_string <- "2020-03-15"
cutoff <- ymd(cutoff_string)
symptom_threshold <- 0

summed_data <- joined %>%
  filter(incident_date >= cutoff) %>%
  filter(covid_indicator > symptom_threshold) %>%
  group_by(NAME, total_population_estimate) %>%
  count() %>%
  mutate(rate_per_1000 = round(n/total_population_estimate * 1000)) %>%
  ungroup() %>%
  st_as_sf()

pre_period <- joined %>%
  filter(incident_date < cutoff) %>%
  filter(covid_indicator > symptom_threshold)

post_period <- joined %>%
  filter(incident_date >= cutoff) %>%
  filter(covid_indicator > symptom_threshold)

days_pre <- as.numeric(range(pre_period$incident_date)[2] - range(pre_period$incident_date)[1])
days_post <- as.numeric(range(post_period$incident_date)[2] - range(post_period$incident_date)[1] )

pre_period_summed <- pre_period %>%
  group_by(NAME, total_population_estimate) %>%
  count() %>%
  mutate(rate_per_1000 = (n/total_population_estimate * 1000/days_pre)) %>%
  ungroup() %>%
  st_as_sf()

post_period_summed <- post_period %>%
  group_by(NAME, total_population_estimate) %>%
  count() %>%
  mutate(rate_per_1000 = (n/total_population_estimate * 1000/days_post)) %>%
  ungroup() %>%
  st_as_sf()
```
```{r, fig.height = 6}
#BAMMtools::getJenksBreaks(c(pre_period_summed$rate_per_1000, post_period_summed$rate_per_1000), 7)
color_scale <- colorBin("BuPu", c(0, 0.4), c(0, 0.02, .05, .09, .13, .19, .27, 0.4))

leaflet(width = "100%") %>%
  #addTiles() %>%
  addMapboxGL(style = "mapbox://styles/mapbox/light-v9") %>%
  addMapPane("border", zIndex = 410) %>%
  addPolygons(data = pre_period_summed,
              color = "#444444", weight = 0.5, smoothFactor = 0.5,
              opacity = 1.0, fillOpacity = 0.7,
              fillColor = ~color_scale(rate_per_1000),
              label = ~map(glue("<strong>{NAME}</strong><br/>
                                COVID-like Incident Rate Per 1000: {round(rate_per_1000, 2)}"), htmltools::HTML),
              group = "Pre COVID-19 Era") %>%
  addPolygons(data = post_period_summed,
              color = "#444444", weight = 0.5, smoothFactor = 0.5,
              opacity = 1.0, fillOpacity = 0.7,
              fillColor = ~color_scale(rate_per_1000),
              label = ~map(glue("<strong>{NAME}</strong><br/>
                      COVID-like Incident Rate Per 1000: {round(rate_per_1000, 2)}"), htmltools::HTML),
              group = "During COVID-19 Era") %>%
  addPolylines(data = city_border, color="black", weight = 3, opacity = 0.8, options = pathOptions(pane = "border")) %>%
  addLegend("bottomright", pal = color_scale, values = post_period_summed$rate_per_1000,
            title = "Incident Rate Per 1000",
            opacity = .8) %>%
  addLayersControl(baseGroups = c("Pre COVID-19 Era", "During COVID-19 Era"),
                   options = layersControlOptions(collapsed = FALSE))
```

