---
title: "Data Profiling"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

<style>
  .col2 {
    columns: 2 200px;         /* number of columns and width in pixels*/
    -webkit-columns: 2 200px; /* chrome, safari */
    -moz-columns: 2 200px;    /* firefox */
  }
  .col3 {
    columns: 3 100px;
    -webkit-columns: 3 100px;
    -moz-columns: 3 100px;
  }
</style>


```{r libraries, include=FALSE, message=FALSE, echo=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, error = FALSE, warning = FALSE)
# install.packages("dplyr")
library(dplyr)
library(ggplot2)
library(purrr)
library(sf)  
library(venn)
library(ggthemes)
library(DataExplorer)
```

```{r functions}

check_calc <- function(vec) {
  blanks <- 0L
  true_na <- 0L
  written_na <- 0L
  len <- length(x = vec)
  for (elem in vec) {
    if (is.na(x = elem)) {
      true_na <- true_na + 1L
    } else if (elem == "na") {
      written_na <- written_na + 1L
    } else if (elem == "") {
      blanks <- blanks + 1L
    }
  }
  percent_complete <- (len - (blanks + true_na + written_na)) / len
  unique_values <- length(unique(vec))
  tibble(blanks = blanks,
         true_na = true_na,
         written_na = written_na,
         percent_complete = percent_complete,
         unique_values = unique_values)
}
check_complete <- function(df) {
  z <- deparse(substitute(df))
  map_df(.x = df, .f = check_calc) %>%
    mutate(column = colnames(df)) %>%
    mutate(set = print(z))  %>%
    select(set, column, blanks, true_na, written_na, percent_complete, unique_values)
}
```

```{r}
#Load data 
library(readr)
fairfax_housing_2018_geo <- read_csv("~/git/dspg20broadbandERS/data/fairfax-data/fairfax_housing_2018_geo.csv")

first_six <- fairfax_housing_2018_geo %>%
            select(PARCEL_ID, NUM_UNITS, HOUSING_TYPE, YEAR_BUILT, LONGITUDE, LATITUDE)
```




```{r eval = F}
# To find the no. of NAs in the variable 
sum(is.na(fairfax_housing_2018_geo$PARCEL_ID))
sum(is.na(fairfax_housing_2018_geo$NUM_UNITS))
sum(is.na(fairfax_housing_2018_geo$HOUSING_TYPE))
sum(is.na(fairfax_housing_2018_geo$YEAR_BUILT))
# 453 NAs in the YEAR_BUILT variable 
sum(is.na(fairfax_housing_2018_geo$LONGITUDE))
sum(is.na(fairfax_housing_2018_geo$LATITUDE))

```

```{r}
#completeness of variables
check_complete(first_six) %>% knitr::kable()
```

```{r}
#General exploration of the variables
plot_intro(first_six)

#distribution of types of housing units
housing_dist_plot <- ggplot(first_six, aes(x=HOUSING_TYPE)) +
  geom_bar(fill="light blue", position="stack") +
                   geom_text(stat = "count", aes(y = ..count.., label = ..count..), position = "identity", vjust=-0.3 ) +
  labs(x = "Hosuing Type", y = "Count")+
  theme(
    axis.title.x = element_text(size = 10, face = "bold"),
    axis.title.y = element_text(size = 10, face = "bold.italic")
  )
housing_dist_plot

# DataExplorer method to plot Housing Type
plot_bar(first_six$HOUSING_TYPE) 

#There are only 8 mobile houses in the entire dataset. 

################################################################################

#distribution of the year houses were built in
plot_histogram(first_six$YEAR_BUILT)

################################################################################

#number of units distribution by Year built
#Most houses were built in the mid to late 1900s. 
num_units <- first_six[, c("NUM_UNITS", "YEAR_BUILT")]
plot_scatterplot(num_units, by="NUM_UNITS")

# 26 houses were built before the year 1800
house_1700s <- first_six %>%
                filter(YEAR_BUILT < "1800")
house_1700s
count(house_1700s)

#Only 1 house was built in most years
house <- house_1700s[, c("NUM_UNITS", "YEAR_BUILT")]
plot_scatterplot(house, by="NUM_UNITS")


```




